### ISSUE TITLE
Repl test failing for "empty command evaluates to undefined"

### ISSUE THREAD

**Issue by mikeyhew** [jashkenas/coffeescript#4161] opened 2015-12-18 19:54 UTC
Stack trace is below. Steps to reproduce:

``` bash
git clone https://github.com/jashkenas/coffeescript.git coffeescript-fresh
cd coffeescript-fresh
npm install
cake test
```

``` bash
$ node -v
v5.3.0
$ jison --version
0.4.15
```

Last git commit = b8403bfa97e8aa662781af30d38a8c953119ab12

```
failed 1 and passed 651 tests in 4.83 seconds 

  empty command evaluates to undefined 
  AssertionError: Expected undefined to equal coffee> 
  at global.eq (coffeescript-fresh/Cakefile:313:14)
  at coffeescript-fresh/test/repl.coffee:69:3
  at Function.<anonymous> (coffeescript-fresh/test/repl.coffee:38:17)
  at global.test (coffeescript-fresh/Cakefile:276:12)
  at testRepl (coffeescript-fresh/test/repl.coffee:38:3)
  at Object.<anonymous> (coffeescript-fresh/test/repl.coffee:67:1)
  at Object.<anonymous> (coffeescript-fresh/test/repl.coffee:1:1)
  at Module._compile (module.js:398:26)
  at Object.exports.run (coffeescript-fresh/lib/coffee-script/coffee-script.js:134:23)
  at runTests (coffeescript-fresh/Cakefile:353:22)
  at Object.action (coffeescript-fresh/Cakefile:369:12)
  at helpers.extend.invoke (~/.nvm/versions/node/v5.3.0/lib/node_modules/coffee-script/lib/coffee-script/cake.js:44:26)
  at Object.exports.run (~/.nvm/versions/node/v5.3.0/lib/node_modules/coffee-script/lib/coffee-script/cake.js:70:20)
  at Object.<anonymous> (~/.nvm/versions/node/v5.3.0/lib/node_modules/coffee-script/bin/cake:7:38)
  at Module._compile (module.js:398:26)
  at Object.Module._extensions..js (module.js:405:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at startup (node.js:141:18)
  at node.js:980:3

  function () {
      return fn(input, output, repl);
    }
```

**Comment by GeoffreyBooth** [comment] 2017-04-18 07:39
Duplicate of #4502.

**Closed by GeoffreyBooth** 2017-04-18 07:39 UTC
