### ISSUE TITLE
Parser error: "unexpected break" after parens-less function call on object

### ISSUE THREAD

**Issue by ilikebits** [jashkenas/coffeescript#4284] opened 2016-07-16 22:29 UTC
The following doesn't parse:
```coffee
if f a: b
  break
```

This occurs at least with any kind of statement with a parens-less function call on an object. See:
```coffee
while f a: b
  break
```

**Comment by vendethiel** [comment] 2016-07-17 14:14
Duplicate of #3737, #3595.

**Closed by vendethiel** 2016-07-17 14:14 UTC
Labels: duplicate
