### ISSUE TITLE
Inconsistent behavior with `::` and `is`

### ISSUE THREAD

**Issue by za-creature** [jashkenas/coffeescript#3978] opened 2015-05-11 12:57 UTC
Input:

```coffee
typeof Object is 'object'
typeof Object:: is 'object'
```

Output:

```javascript
// Generated by CoffeeScript 1.9.2
(function() {
  typeof Object === 'object';

  typeof Object.prototype.is('object');

}).call(this);
```

**Comment by vendethiel** [comment] 2015-05-11 15:55
See #1601 !

**Comment by michaelficarra** [comment] 2015-05-11 15:56
Duplicate of https://github.com/jashkenas/coffeescript/issues/1477

**Closed by vendethiel** 2015-05-11 15:55 UTC
Labels: duplicate
