### ISSUE TITLE
prototype (::) syntax is ambigous

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#4104] opened 2015-09-21 22:56 UTC
i'm trying to check if an object has a prototype-

```coffee
if a::b then c      # specific property check - ok
if a:: and b then c # no property specified - not ok
```

the latter example compiles to `if (a.prototype.and(b))`, but the intention was `if (a.prototype && b)`.

the fix is to treat spaces around `.prototype.` vs. `::` differently. ie.

```coffee
a::b       #=> a.prototype.b
a:: b      #=> a.prototype(b)
a::b and c #=> a.prototype.b && c
a:: and c  #=> a.prototype && c
```

in the meantime, the workaround is to use parens-

```coffee
if (a::) and b then c
```

**Comment by michaelficarra** [comment] 2015-09-21 22:58
Duplicate of #1601. The unary form of `::` will be removed... some day. Don't use it.

**Closed by michaelficarra** 2015-09-21 22:58 UTC

**Comment by bcherny** [comment] 2015-09-21 23:01
sgtm. thanks for the quick response.
