### ISSUE TITLE
new.target fails

### ISSUE THREAD

**Issue by rafikalid** [jashkenas/coffeescript#5032] opened 2018-04-14 23:52 UTC
as you know, new.target contains the current object when "new" is used with a function (as contructor)
we use this as flag to detect the use of "new" keyword.

Coffeescript compiler fails when using this expression, so we need to use javascript injection instead.

Expected behaviour:
"new.target" should be used without any problem

**Comment by GeoffreyBooth** [comment] 2018-04-15 19:49
Duplicate of #4609.

**Closed by GeoffreyBooth** 2018-04-15 19:49 UTC
