### ISSUE TITLE
Lexer: Within inline `if` block, a `throw` that takes implicit object will split the object into multiple objects

### ISSUE THREAD

**Issue by KarlPurk** [jashkenas/coffeescript#3199] opened 2013-10-10 08:30 UTC
I apologise if this has already been reported, I did search the issues but there are lots related to "throw".  Also, this may not be an issue, but I wanted to double check anyway.

When throwing exceptions the following syntax does not compile correctly:

```
if 1 then throw
    type: 'a'
    msg: 'b'
```

The above coffeescript compiles to the following:

```
if (1) {
  throw {
    type: 'a'
  };
}

({
  msg: 'b'
});
```

In order for this to compile we must use one of the following variations:

```
if 1 then throw type: 'a', msg: 'b'
```

or

```
if 1 then throw {
    type: 'a'
    msg: 'b'
}
```

or

```
if 1 
    throw
        type: 'a',
        msg: 'b'
```

Is this intended?  Or are we missing out on a nicer syntax for throwing exceptions?

Thanks!

**Comment by GeoffreyBooth** [comment] 2017-04-27 06:24
Duplicate of #1263. The issue is the object without braces as part of a statement. That would be nice to fix, if someone feels like submitting a PR; but the workaround is to just add braces, or define the object into a variable before `throw` or `return`ing it.

**Comment by GeoffreyBooth** [comment] 2017-05-01 01:11
Actually it’s not a duplicate of #1263. Possibly a duplicate of #4150.

**Comment by GeoffreyBooth** [comment] 2017-05-06 03:18
One more try: maybe a duplicate of #2998.

**Closed** 2017-07-09 17:29 UTC
Labels: bug, priority
