### ISSUE TITLE
[CS2] May offer an compile option use let instead of var

### ISSUE THREAD

**Issue by IamIpanda** [jashkenas/coffeescript#4639] opened 2017-08-13 01:56 UTC
I have read the paragraph `let and const: block-scoped and reassignment-protected variables` on the coffeescript v2 website, But I want:
May you offer an option, make coffeescript ALL USE `let` instead of `var` in compiled code as it's also `only one type of variable`. Using `var` sometimes trouble me like in the code under:
```
fs = []
a = [1,2,3,4,5]
for i in a
	fs.push -> console.log i
f.call this for f in fs
```
If I'm asking for a selection whose conclusion had been made, I'm sorry and just close this.

**Comment by GeoffreyBooth** [comment] 2017-08-13 23:24
Duplicate of #4255.

**Closed by GeoffreyBooth** 2017-08-13 23:24 UTC
