### ISSUE TITLE
Coffeescript private and pritect class fields (solution)

### ISSUE THREAD

**Issue by Maxmaxmaximus** [jashkenas/coffeescript#4195] opened 2016-02-01 12:19 UTC
a record video in which i tich you how add private and pritect into coffeescript  https://www.youtube.com/watch?v=i_ksumTO2_0

This is my last attempt.... I can not do it anymore

**Comment by Maxmaxmaximus** [comment] 2016-02-01 12:50
just use namespace '_' or   space+_   ' _' то store private incapsulated props like protected.
and  use '_' + uniqueClassNamespaces to store private class props

**Comment by vendethiel** [comment] 2016-02-01 13:06
Seems to be a duplicate of #4190.

**Comment by Maxmaxmaximus** [comment] 2016-02-01 13:07
@vendethiel  arguments will be?

**Closed by vendethiel** 2016-02-01 13:06 UTC

**Comment by vendethiel** [comment] 2016-02-01 13:07
Same as last time and the times before.

**Comment by Maxmaxmaximus** [comment] 2016-02-01 13:08
@vendethiel I rejected your arguments

**Comment by vendethiel** [comment] 2016-02-01 13:08
ok

**Comment by Maxmaxmaximus** [comment] 2016-02-01 13:08
@vendethiel then we can get access from the outside does not private property

**Comment by Maxmaxmaximus** [comment] 2016-02-01 13:10
@vendethiel I rejected your arguments. therefore you are wrong. adds private and protect props.

**Comment by vendethiel** [comment] 2016-02-01 13:10
https://github.com/jashkenas/coffeescript/search?q=private&type=Issues&utf8=%E2%9C%93

**Comment by vendethiel** [comment] 2016-02-01 13:11
I think I'm going to go ahead and lock this as well. I really wish I wouldn't have to, but..

**Comment by michaelficarra** [comment] 2016-02-01 15:20
@vendethiel Feel free to lock any other inflammatory threads created by @maxmaxmaximus as soon as they are opened. We don't need these things to carry on.

@maxmaxmaximus If you open an issue like this again, I will report your account to GitHub. They have banned users for far less.
