### ISSUE TITLE
Post install step for coffee-script failing on Windows 8

### ISSUE THREAD

**Issue by peternhale** [jashkenas/coffeescript#4813] opened 2017-12-01 20:31 UTC
During the post install step of coffee-script on a Windows 8 the warning recently added is failing. Coffee-script is being referenced by a third party dependency, so I cannot fix that dependency.

> coffee-script@1.12.8 postinstall <redacted>\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:624:30)
    at evalScript (bootstrap_node.js:461:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:607:3
npm WARN force-language-services@42.0.1-6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by GeoffreyBooth** [comment] 2017-12-01 20:38
Please refresh your cache. Duplicate of https://github.com/jashkenas/coffeescript/issues/4805

**Closed by GeoffreyBooth** 2017-12-01 20:38 UTC
