### ISSUE TITLE
Spread operator in list comprehension.

### ISSUE THREAD

**Issue by rill-js** [jashkenas/coffeescript#3971] opened 2015-05-01 15:47 UTC
Not sure if this has been discussed before, but I think this would be convenient for flattening the resulting arrays of a comprehension.

```coffeescript
    arrays = [[1, 2], [3,4]]
    flat = (array... for array in arrays)

    flat is [1, 2, 3 4]
```

With the spread simply acting as a spread on the "results.push" in the comprehension, or doing a concat to the current list instead.

Currently this can be done by:

```coffeescript
   flat = [].concat((array for array in arrays)...)
```

**Comment by lydell** [comment] 2015-05-01 16:16
Duplicate of #3949.

**Comment by vendethiel** [comment] 2015-05-01 17:06
Thanks @lydell!

**Closed** 2015-05-01 17:06 UTC
