### ISSUE TITLE
CLI: Custom output file names

### ISSUE THREAD

**Issue by am11** [jashkenas/coffeescript#3526] opened 2014-06-30 10:37 UTC
In many node-based source-to-source trans-compilers,  there is an option to specify custom output filename-with-path. 

In CoffeeScript the `--output` switch takes target folder, meaning you cannot specify custom filename! We are facing a hard time with it in [editor extension](http://github.com/madskristensen/webEssentials2013/). Can you please add a condition:

``` javascript
if(fs.lstatSync(custom_target_filename_with_custom_path_and_custom_extension).isDirectory())
    // continue with current logic
else if(fs.existsSync(custom_target_filename_with_custom_path_and_custom_extension))
    // use path.basename(custom_target) and
    // PLEASE "custom_target + .map" for map filename
    // (do not change extension for .map, just append it)
```

Considering that Less, Sass (node-sass), LiveScript and SweetJS, all produce `targetName.TargetExtension.map`. Less and Sass: `target.css.map` and LiveScript, TypeScript and SweetJs `target.js.map`. 

So please follow the conventions or at least give us sufficient options so we can configure output file names.

To recapitulate, the compiler should:
- Accept custom path with custom extension for target file.
- Accept custom path for map file.
- Produce map file with double extension: `myCoffee.js.map`

**Comment by sedabull** [comment] 2015-01-16 06:36
+1

**Comment by chocolateboy** [comment] 2015-04-05 01:27
1. :+1:
2. This is a duplicate of #2870.
3. A workaround is to use: `coffee -p source.coffee > output.js`

**Comment by GeoffreyBooth** [comment] 2017-04-28 20:03
Closing in favor of #2870.

**Closed by GeoffreyBooth** 2017-04-28 20:03 UTC
