### ISSUE TITLE
Conditional on first property breaks object definition

### ISSUE THREAD

**Issue by mzgajner** [jashkenas/coffeescript#4172] opened 2016-01-04 11:39 UTC
This works:
```
obj =
  a: 123
  b: yes if someVar
```
This breaks with `Error on line 2: unexpected newline `:
```
obj =
  a: 123 if someVar
  b: yes
```
Alternatively, if you're not assigning it to a var, it doesn't break:
```
a: 123 if someVar
b: yes
```
BUT it doesn't produce `{ a: someVar ? 123 : void 0, b: true }` as one would expect, it instead produces two objects:
```
if (someVar) {
  ({
    a: 123
  });
}

({
  b: true
});
```
If at the end of a function, only second object is returned.

Tested with live runner on coffeescript.org.

**Comment by vendethiel** [comment] 2016-01-04 12:44
Duplicate of #3534

**Closed by vendethiel** 2016-01-04 12:44 UTC
