### ISSUE TITLE
Breaking require() shenanigans

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [jashkenas/coffeescript#3955] opened 2015-04-26 07:24 UTC
So, I've been having some strange bugs in my application (with a rather complex load-topology), and I've finally traced it down to this really strange behaviour.

In plain JavaScript, here's the expected Node functionality:

```
> cat a.js                       |  > cat b.js                 |  > cat c.js
module.exports = 'foo'           |  module.exports = '1: ' +   |  module.exports = '2: ' +
console.log(require('./b.js'))   |     require('./a.js')       |     require('./a.js')
                                 |                             |
module.exports = 'bar'           |                             |
console.log(require('./c.js'))   |                             |

> node a.js
1: foo
2: bar
```

However, when executed through CoffeeScript, things get weird:

```
> cat a.coffee                   |  > cat b.coffee             |  > cat c.coffee
module.exports = 'foo'           |  module.exports = '1: ' +   |  module.exports = '2: ' +
console.log require './b.coffee' |     require './a.coffee'    |     require './a.coffee'
                                 |                             |
module.exports = 'bar'           |                             |
console.log require './c.coffee' |                             |

> coffee a.coffee
{}
2: bar
1: bar
2: bar
```

… what!?

Clearly, I don't understand how CoffeeScript injects itself into the module-loading system; but regardless of how it's _supposed_ to work, this is pretty unintuitive behaviour.

**Comment by michaelficarra** [comment] 2015-04-28 01:33
Confirmed. I have no idea why this is happening. It can also be reproduced all the way back in 0.9.6 (the earliest version I tested). CoffeeScriptRedux does not have this problem.

**Comment by GeoffreyBooth** [comment] 2017-05-06 06:41
The `coffee` command is only intended for compiling and simple debugging. It’s not a replacement for the `node` command. If someone can fix this I would be happy to accept a PR, but it’s out of scope for `coffee` to handle every case that `node` can.

**Closed by GeoffreyBooth** 2017-05-06 06:41 UTC
Labels: bug
