### ISSUE TITLE
Proposal: Multiple catch blocks with guard

### ISSUE THREAD

**Issue by za-creature** [jashkenas/coffeescript#4333] opened 2016-10-05 13:38 UTC
I want dis:

```coffeescript
try
  throw new Error("foo")
catch e when e.message is "foo"
  console.log("caught")
```

## Behavior

If a catch handler is guarded, it will only execute the block if the guard condition matches. If it doesn't, the error is propagated to the next catch statement (guarded or not). If a try block only has guarded catch statements, and no guards match, the error is thrown like a try / finally block.

If there is a unguarded catch block, it must be the last one.

## Use cases

* easier to use this pattern:
```coffeescript
try
  yield doSomethingAsync()
catch e
  if not e instanceof WellKnownAndNotNetworkError
    throw e  # don't want to handle network errors here
  yield doSomeErrorHandling()
```
* ~~less~~ easier-to-read code when writing multiple error handlers:
```coffeescript
try
  yield doSomethingAsync()
catch e
  if e instanceof Foo
    yield doHandleFooErrors()
  else if e instanceof Bar
    yield doHandleBarErrors()
  else
    rethrowOrHandle()
```

## Inspiration

* https://docs.python.org/2/tutorial/errors.html#handling-exceptions
* http://bluebirdjs.com/docs/api/catch.html#filtered-catch

----------
If there's interest in this and a maintainer gives me the go-ahead, I can give this a shot.

**Comment by lydell** [comment] 2016-10-05 13:51
Duplicate of #1453, #1763.

**Closed by lydell** 2016-10-05 13:51 UTC

**Comment by za-creature** [comment] 2016-10-05 14:04
Oh, sorry, didn't see the old ones. In the end, it's not my call but imo it's worth revisiting because:

* the other proposals focused on typed errors, while this is more along the lines of a guarded for (the guard can take any expression, it doesn't have to be an instance check; it can also do a property check as well)
* yield is now a thing and because it's not compatible with for..in, it's mostly used for async code
* within the realms of promises, the filtered catch has proven itself to be fairly useful
* while exception types are not to be relied upon, this can still be used with custom error classes for flow-control

Just my $0.02, I won't push for this any further

**Comment by phil294** [comment] 2019-11-28 09:34
I agree with za-creature that this should be reopened @lydell, as this is not only about type errors and he raises some very valid points.

For example, this makes sense with property checking:
```
try
    etc()
catch e
    if e.status == 404
        return
    throw e
```
becomes
```
try
    etc()
catch e when e.status != 404
```
I was surprised this was not part of the language when I tried to code it. Conditional catches seems somewhat of an antipattern but it looks intuitive and clean.

**Comment by Inve1951** [comment] 2019-11-29 16:51
FYI, this works today:
```coffee
try something()
catch err then throw err unless err.status is 404
```
Same goes for this:
```coffee
try something()
catch err then switch
  when err.status is 404
    return
  when 500 <= err.status <= 599
    throw new ServersideError err
  else throw err
```
You can also use `catch` for binding only and do something with the error outside the `catch` block since it's scoped like any other variable in CoffeeScript.
