### ISSUE TITLE
Existential operator inconsistent and/or buggy when chained?

### ISSUE THREAD

**Issue by wuya666** [jashkenas/coffeescript#5243] opened 2019-11-21 16:41 UTC
### Input Code
```coffee
a = 5
b = c ? d ? e ? a ? 10
```

### Expected Behavior
`b` should be assigned 5 (the value of `a`)

### Current Behavior
a horrible runtime error of `ReferenceError: d is not defined` as it transpiles into 
```javascript
var a, b, ref, ref1, ref2;

a = 5;

b = (ref = (ref1 = (ref2 = typeof c !== "undefined" && c !== null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
on the other hand
```coffee
a = 5
b = c ? a ? 10
```
works as it transpiles into
```javascript
var a, b, ref;

a = 5;

b = (ref = typeof c !== "undefined" && c !== null ? c : a) != null ? ref : 10;
```
so somehow the first undefined variable is checked with `typeof` by the existential operator but the variables preceding the following chained existential operators are not checked with `typeof` which is strange and doesn't make much sense.

### Possible Solution
I think a very simple solution would be to declare all the variables to be checked by the existential operators (except, of course, if they are already declared in an outer scope) in the transpiled javascript code like this
```javascript
var a, b, c, d, e, ref, ref1, ref2;

a = 5;

b = (ref = (ref1 = (ref2 = c != null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
Then there will be no need for a special `typeof` check at all, and the unassigned variables all have default `undefined` value which is consistent with the supposed "non-existence" of the variables (and they still have the `typeof` value of `"undefined"`).

Another possible solution is to consistently do the `typeof` check for all the variables preceding the chained existential operators in the transpiled javascript code, something like
```javascript
var a, b, ref, ref1, ref2, ref3, ref4, ref5;

a = 5;

b = (ref = (ref1 = (ref2 = (ref3 = typeof c !== "undefined" ? c : undefined) != null ? ref3 : (ref4 = typeof d !== "undefined"? d : undefined)) != null ? ref4 : (ref5 = typeof e !== "undefined" ? e : undefined)) != null ? ref1 : a) != null ? ref : 10;
```
this looks messy but at least it's consistent and don't throw a runtime error.

### Context
I'm aware that this runtime error can be "fixed" by something like
```coffee
a = 5
b = c ? (d ? (e ? (a ? 10)))
```
but IMHO that looks a very ugly hack that doesn't make much sense. If I put an existential operator after a variable, I expect it should not throw a horrible runtime error of `<variable name> is not defined` and it should not matter if it's left-associative or right-associative. The current behavior IMHO doesn't make any sense in terms of logic, semantics, or common sense.

### Environment

* CoffeeScript version: 2.4.1
* Node.js version: 12.13.1

**Comment by vendethiel** [comment] 2019-11-21 16:54
Duplicate of #2199

**Closed by vendethiel** 2019-11-21 16:54 UTC

**Comment by wuya666** [comment] 2019-11-21 17:08
I don't think this is a duplicate of #2199 since like I mentioned I don't think it's an issue with the left-associativity of the operator. I think it's more about inconsistent type checking with the `typeof` operator in the transpiled JavaScript code, and the possible solutions I wrote here doesn't change the left-associative nature of the existential operator.

**Comment by vendethiel** [comment] 2019-11-21 18:04
So, if I understand correctly what you want is that `a ? b` behaves like `a ? (b ? null)` instead of of it currently behaves?

**Comment by wuya666** [comment] 2019-11-22 08:49
The result should be more similar to `a ? (b ? undefined)` if you put it this way, as `undefined` and `null` are different, but then like I said in the OP I don't think changing the existential operator to right-associative is a good or sensical solution. 

I think `b = c ? d ? e ? a ? 10` should stay equivalent to `b = ((((c ? d) ? e) ? a) ? 10)` as how the existential operator is currently designed, since changing the operator associativity leads to unnecessary change in semantics which can cause problems. Just that whatever the operator's associativity is designed, there should not be an ugly runtime error about undefined variables which is more like a bug for the existential operators (IMO the very purpose of the existential operators is so that we will not be getting runtime errors on non-existent variables/objects)

That's why for the possible solution, I don't think the transpiled Javascript code needs to change at all except declaring some extra undefined variables related to the existential operators. Right now 
```coffee
a = 5
b = c ? d ? e ? a ? 10
```
transpiles into
```javascript
var a, b, ref, ref1, ref2;

a = 5;

b = (ref = (ref1 = (ref2 = typeof c !== "undefined" && c !== null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
which produces an ugly runtime error, but just by simply declaring the extra undefined variables beforehand everything will work fine
```javascript
var a, b, c, d, e, ref, ref1, ref2;

a = 5;

b = (ref = (ref1 = (ref2 = typeof c !== "undefined" && c !== null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
and the overall semantics are not affected as variables `c`, `d`, and `e` stay `undefined`. The main part of the transpiled code related to the existential operators 
```javascript
b = (ref = (ref1 = (ref2 = typeof c !== "undefined" && c !== null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
does not need to be changed at all, although I do think it'd be nicer and look more consistent if we can tidy it up into something like
```javascript
b = (ref = (ref1 = (ref2 = c != null ? c : d) != null ? ref2 : e) != null ? ref1 : a) != null ? ref : 10;
```
This is what I think how this "bug" in the chaining existential operators could be fixed, without trying to modify how the operator's associativity is designed. This way it will not cause any problem to any existing code which may depend on the left-associative nature of the existential operators. It will only be a problem if some code has some logic that actually _depends_ on the existential operators throwing a runtime error of `x is undefined`, which doesn't make sense anyway IMO.
