### ISSUE TITLE
proposal: operator `=.` (example: `a =. b` -> `a = a.b`)

### ISSUE THREAD

**Issue by blitmap** [jashkenas/coffeescript#4232] opened 2016-03-20 04:15 UTC
Title says it all - I just want to propose a shorthand form for this:

```javascript
someVeryLongIdentifier = someVeryLongIdentifier.member
```

This is different and **unrelated** to destructuring.

Currently I come across a need for this when I am yielding values from an iterator:

```coffeescript
iterator = @someGenerator()
until (origin = iterator.next()).done
    iterItem = iterItem.value
```

I want to write: `iterItem =. value`

A more "complex" example might be:

```coffeescript
a.b.c =. d
```

Which would become:

```javascript
a.b.c = a.b.c.d
```

This proposal would have no impact on the meaning of existing operators in Coffeescript's grammar, as this operator does not exist.  It is a very, very simple transformation and I welcome discussion of it's very minimal merits.  Perhaps this operator is an opportunity for something more complex.  I am proposing this simply to avoid writing long [but meaningful] identifiers twice.

**Comment by lydell** [comment] 2016-03-20 07:15
Duplicate of #3793.

**Closed by lydell** 2016-03-20 07:15 UTC

**Comment by blitmap** [comment] 2016-03-20 07:46
Okay... so this is a duplicate of the other proposal (#3793) - I had trouble searching for this (sorry).

That other proposal wasn't taken up because of how it looked visually.

jashkenas said he didn't like `a .= b()` because `b()` looked like a free-floating function not associated with `a`.

I believe mine [visually] corrects that.  `a =. b()` is better
