### ISSUE TITLE
Error while installing Coffee-script@1.12.8 'invalid or unexpected token' 

### ISSUE THREAD

**Issue by eashi** [jashkenas/coffeescript#4805] opened 2017-11-30 08:33 UTC
When I try to install like below I get the error.
I am using NPM 5.6.0 on a Windows 10 Machine .

> npm install -g coffee-script@1.12.8
> C:\Users\myuser\AppData\Roaming\npm\cake -> C:\Users\myuser\AppData\Roaming\npm\node_modules\coffee-script\bin\cake
> C:\Users\myuser\AppData\Roaming\npm\coffee -> C:\Users\myuser\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee
> 
> > coffee-script@1.12.8 postinstall C:\Users\myuser\AppData\Roaming\npm\node_modules\coffee-script
> > node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'
> 
> [eval]:1
> 'if
> ^^^
> SyntaxError: Invalid or unexpected token
>     at createScript (vm.js:56:10)
>     at Object.runInThisContext (vm.js:97:10)
>     at Object.<anonymous> ([eval]-wrapper:6:22)
>     at Module._compile (module.js:570:32)
>     at evalScript (bootstrap_node.js:354:27)
>     at run (bootstrap_node.js:123:11)
>     at run (bootstrap_node.js:390:7)
>     at startup (bootstrap_node.js:122:9)
>     at bootstrap_node.js:505:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2017-11-30T08_12_56_775Z-debug.log

**Comment by mapohjola** [comment] 2017-11-30 08:40
Experiencing the same thing with npm 3.10.10 on win 10

**Comment by Liam-Ryan** [comment] 2017-11-30 08:58
Seeing the same with npm 5.3.0

**Comment by vendethiel** [comment] 2017-11-30 09:11
To be clear, if you *are* able to change your dep, you should use `coffeescript` instead of `coffee-script`. The issue remains for nested deps.

**Comment by sharmasourabh** [comment] 2017-11-30 09:18
Same issue is there for Windows 10 and npm 5.5.1

**Comment by weihsth** [comment] 2017-11-30 09:21
Same issue here Windows 8.1 & npm 3.5.2. Karma is loading the coffeescript package.

**Comment by 4O4** [comment] 2017-11-30 09:33
I don't want to hurry you, but is there any ETA? This is a critical issue for most of us :)

**Comment by vadimDidenko** [comment] 2017-11-30 09:34
Why did not you use "deprecated" field from package.json?
We are waiting for your fix, since we have dropped the production release now. We use a third-party library that uses your library.

**Comment by garvik** [comment] 2017-11-30 09:35
As a quick workaround, you can reference an older version of the library in your package.json.
"coffee-script": "1.12.7" worked in my case.

**Comment by 4O4** [comment] 2017-11-30 09:38
My package.json looks funny now with typescript and coffeescript side by side :smile: But it works, thanks @garvik 

![image](https://user-images.githubusercontent.com/4274691/33423906-78b36d42-d5ba-11e7-8090-847509636e3d.png)

**Comment by pmaza** [comment] 2017-11-30 09:40
The problem is that many third-party libraries use this library.

**Comment by meowthing** [comment] 2017-11-30 09:43
+1 @pmaza. I'm new to node, is there a way to enforce the use of a version for a package globally?

**Comment by henrikmerlander** [comment] 2017-11-30 09:45
@garvik 's solution worked for me, even though I have only third party dependencies on this library.

**Comment by vendethiel** [comment] 2017-11-30 09:46
> I don't want to hurry you, but is there any ETA? This is a critical issue for most of us :)

I don't have a npm access to this. Paging @GeoffreyBooth.

**Comment by pmaza** [comment] 2017-11-30 09:50
@meowthing I've just solved it right now installing "coffee-script@1.12.7" as a dev dependency.
Thanks @garvik!!

**Comment by weihsth** [comment] 2017-11-30 09:54
Added "coffee-script": "1.12.7" as devDependency solved it. Thanks @all

**Comment by ArturChe** [comment] 2017-11-30 10:05
I suppose that windows machine can't recognize the string argument wrapped in single quotes.
It should be wrapped in double quotes instead.

**Comment by GMouron** [comment] 2017-11-30 10:58
Would be great to unpublish the package or publish a fix. I think this is breaking many builds on Windows (it's breaking ours at least and we don't have a direct dependency on this package)

**Comment by alan-agius4** [comment] 2017-11-30 11:01
Or simplify this
https://github.com/jashkenas/coffeescript/blob/1/package.json#L31

By just doing a console.warn and avoid all fancy things

**Comment by guoruiak** [comment] 2017-11-30 11:03
Same issue is there for Windows 7 and npm 6.11.0

**Comment by BhupenderAgarwal24** [comment] 2017-11-30 11:11
I am having the same issue where coffee-script is an internal dependency of some third party module due to which actual installation of our npm module is failing. 

I am using npm 5.4.2 on windows 7.

Please release the fix as soon as possible.

**Comment by ivanromakh** [comment] 2017-11-30 11:12
The same I installed 1.12.1 but vue-cli needs the newest and I can`t install it

**Comment by vadimDidenko** [comment] 2017-11-30 11:13
There are always two ways out, go easy and go the right way. Simple - replace double quotes or replace the library (if possible). Is correct - to make fix as soon as possible

**Comment by ivanromakh** [comment] 2017-11-30 11:18
Thanks:)

**Comment by rducom** [comment] 2017-11-30 11:18
@GeoffreyBooth can you please communicate about an ETA ? Or unpublish the package ?

**Comment by samuelfernandez** [comment] 2017-11-30 11:22
Yes this is just a mess, hard to fix in the dependency tree..

**Comment by niftylettuce** [comment] 2017-11-30 11:42
https://github.com/niftylettuce/email-templates/issues/266

**Comment by Alevale** [comment] 2017-11-30 11:42
This is happening when you execute this command from the **windows CMD**, not from the **mac or linux term**

**Comment by admeister** [comment] 2017-11-30 11:45
Me too when trying to build in VSTS. It's a dependency on jasmine-node - I'm not using it directly.

**Comment by antwan2093** [comment] 2017-11-30 11:51
I'm experiencing this on a mac too, doesn't seem to be a windows CMD specific issue. This was for a new installation of a package we use that depends on coffee-script

**Comment by admeister** [comment] 2017-11-30 11:53
Try @weihsth suggestion of adding coffee-script 1.12.7 to devDependencies, but no joy. 1.12.8 keeps being used.

Is there any ETA on a fix for this??

**Comment by ondrejbase** [comment] 2017-11-30 11:54
I've added coffee-script: "1.12.7" to devDependencies to solve this issue (hopefully temporarily).

**Comment by ThorMutoAsmund** [comment] 2017-11-30 12:27
It is 4:30 am in LA right now. He probably committed this right before going to bed

**Comment by Drag13** [comment] 2017-11-30 12:30
Mac/Windows doesn't meter. But temporary solution with 1.12.8 works for me as well.

**Comment by pete-hotchkiss** [comment] 2017-11-30 12:39
This guys phone is going to be throwing notifications like a crazy mo-fo when he wakes up.

It's the new LeftPad !

**Comment by ArturChe** [comment] 2017-11-30 12:53
LOL Hope he sleeping well with Freddy Krueger!!

**Comment by GMouron** [comment] 2017-11-30 13:04
@admeister In my case, I had to use it to `dependencies` instead of `devDependencies` ¯\\\_(ツ)_/¯

**Comment by xameeramir** [comment] 2017-11-30 13:12
I believe one of my npm module internally needs it because adding

```
  "devDeppendencies": {
    "coffee-script": "1.12.7"
  }
```

didn't solved this issue

**Comment by GMouron** [comment] 2017-11-30 13:15
@xameeramir You have on p to many, if it's a direct copy/paste from your file, that might be the problem.
Otherwise, try adding it to `dependencies`, it worked in my case.

**Comment by pete-hotchkiss** [comment] 2017-11-30 13:54
For mission critical production requirements, there is a work around - but it's not clean.

It involves using a local npm cache too which you publish a clone of v 1.12.7 'bumped' to 1.12.8 and then have your production environment utilise that as your source for packages

```
npm config edit
registry=http://feeds.acme.com/
```
Possible options for server is https://www.npmjs.com/package/sinopia

**Comment by yyx990803** [comment] 2017-11-30 14:23
Would really appreciate a fast fix.

To clarify the severeness of this issue: since this script breaks on Windows, **it essentially breaks all packages that has `coffee-script` as a direct or nested dependency on Windows,** including `vue-cli`. And since this is a nested dependency for us, we'd have to fork or ditch our direct dependency (which is hardly maintained anymore) if a prompt fix isn't possible.

**Comment by xameeramir** [comment] 2017-11-30 14:23
@GMouron Added as direct dep

**Comment by Kylir** [comment] 2017-11-30 14:29
Same issue. I'm using `jasmine-node` and it has `coffee-script` has a dependency.
Build broken on Windows 7 with Node 8.9.1.

**Comment by vendethiel** [comment] 2017-11-30 14:30
> Would really appreciate a fast fix.

People have posted workarounds here.
The people able to publish new versions are @jashkenas , @lydell , and @GeoffreyBooth . You'll need to wait for them to show up. There's not much else to do.

Posting "same issue" doesn't really help with anything.

**Comment by joebits** [comment] 2017-11-30 14:31
We have jasmine-node as a dependency and when I added "coffee-script" : "1.12.7" to our dependencies it picked up this version instead of the latest, which fixed it for us. Will remove it once the real issue is fixed.

**Comment by yyx990803** [comment] 2017-11-30 14:31
@vendethiel there is no workaround for packages that has `coffee-script` as an indirect dependency, because we have no direct control over the version of `coffee-script` to be used.

**Comment by vendethiel** [comment] 2017-11-30 14:36
@yyx990803 I don't see how it is being underestimated. There doesn't seem to be anyone awake with npm push rights. I'm open to suggestions.

**Comment by yyx990803** [comment] 2017-11-30 14:40
@vendethiel no previous comments had pointed out the implication of this bug (breaking all related packages on Windows), so it's worth pointing out. It's meaningful information and not "same issue here."

**Comment by mbodecek** [comment] 2017-11-30 14:40
@yyx990803 correct me if I'm wrong, but any version of coffeescript you specify will get picked up, as long as it fits in version range specified by your third-party library.

**Comment by vendethiel** [comment] 2017-11-30 14:43
@yyx990803 Comments from weihsth, vadimDidenko, pmaza, GMouron, BhupenderAgarwal24, ivanromakh, admeister already pointed that out. I think the point was well understood. It's critical. But there's nothing I/we can do right now.

**Comment by pete-hotchkiss** [comment] 2017-11-30 14:49
When production environments are unable to build - it's beyond critical and the severity should not be underestimated.

Whilst the fix is simple - and there are work arrounds these aren't suitable for everyone and for them, the delay while we wait for a fix is a costly one.

**Comment by yyx990803** [comment] 2017-11-30 14:49
@mbodecek good point! That is indeed a valid workaround before things gets fixed here. Thanks.

**Comment by antwan2093** [comment] 2017-11-30 14:56
@vendethiel even though a workaround is in place, it shows a significant failing in testing and deploying this commit to a package which is incredibly popular and used in lots of popular libraries. Might be worth investigating some more robust push policies/reviewing.

**Comment by vadimDidenko** [comment] 2017-11-30 14:59
For yarn package manager need add ` "resolutions": {
    "coffee-script": "1.12.7"
  }` to package.json

**Comment by ThorMutoAsmund** [comment] 2017-11-30 14:59
Has anyone contacted simon.lydell@gmail.com ? He is in Stockholm and should be awake

**Comment by lluisd** [comment] 2017-11-30 15:07
Same problem here when I tried to install i18n

**Comment by maxbel90** [comment] 2017-11-30 16:11
Using old version of keystone which uses packages that are using coffee-script 1.12.8.
Fixed by adding coffee-script: 1.12.7 to my devDependencies.

**Comment by GeoffreyBooth** [comment] 2017-11-30 16:14
Well, now that we have your attention 😄

I changed `coffee-script` `latest` and `stable` back to 1.12.7 for now.

**Comment by vendethiel** [comment] 2017-11-30 16:15
@GeoffreyBooth thank you :-).

**Comment by sdib** [comment] 2017-11-30 16:29
@GeoffreyBooth thanks

**Comment by GeoffreyBooth** [comment] 2017-11-30 16:55
So I assume the emergency is over, now that `latest` points to 1.12.7?

While you’re here, does anyone know how we could print this error only on direct installs, i.e. when `coffee-script` is in the user’s `package.json`, as opposed to `coffee-script` being installed as a dependency of some other package? Or looked at in another way, within the context of the `postinstall` script is there a way to detect whether we’re being installed directly versus as a dependency? See #4759.

**Comment by alan-agius4** [comment] 2017-11-30 17:24
@GeoffreyBooth I think what you are looking for is something like; (not tested)

```js
const path = require("path");
const rootPkg = path.join(process.cwd(), "package.json");
const pkg = JSON.parse(require(rootPkg)); // you should probably verify that it exists

if ((pkg.dependencies && pkg.dependencies["coffee-script"])
    || pkg.devDependencies && pkg.devDependencies["coffee-script"]) {
 // oops wrong coffee-script installed
} 
```

**Comment by 4O4** [comment] 2017-11-30 17:25
@GeoffreyBooth Why not just use `npm-deprecate` ? It's simple, built-in, fits your scenario and you definitely can't break thousands of random projects with that 😃

**Comment by SwintDC** [comment] 2017-11-30 17:29
@GeoffreyBooth just tested it, the emergency is over

Though I have no clue how we have a dependency on coffee-script: it's not in our package.json and not in the dependency tree when printing it with "npm ls"

**Comment by GeoffreyBooth** [comment] 2017-11-30 17:46
@SwintDC thanks 😄

@4O4 https://github.com/jashkenas/coffeescript/pull/4759#issuecomment-343812014

@alan-agius4 Let’s discuss in #4807. If there’s anyone with Windows or CI environments that can help us test, please check out that PR. I’ll aim to push a fix on Friday night, so that at least there’s the weekend for any flood of new problems. Sorry for the headache everyone.

I have until tonight to `npm unpublish` 1.12.8 if we want, but I’m not sure there’s a point in doing so? The 1.12.8 version can’t be reused even after I unpublish, so the fix will be in 1.12.9 regardless.

**Comment by 4O4** [comment] 2017-11-30 17:59
@GabrielRatener IMHO it makes perfect sense to unpublish 1.12.8. It's faulty release, don't let anyone ever install it again for your own peace of mind.

**Comment by GeoffreyBooth** [comment] 2017-11-30 18:52
Okay, I’ve unpublished `coffee-script@1.12.8` and `coffeescript@1.12.8`.

**Closed** 2017-11-30 18:52 UTC
Labels: bug
