### ISSUE TITLE
Array element presence check quirks

### ISSUE THREAD

**Issue by toncid** [jashkenas/coffeescript#5392] opened 2022-01-17 09:59 UTC
Choose one: is this a bug report or feature request?

Importing a possible **bug report** from: https://stackoverflow.com/questions/70679185/array-element-presence-check-quirks-in-coffeescript

When checking element presence in inline arrays via the `in` keyword, CoffeeScript ignores `indexOf` and rather does that many equality checks.

However, when referring to an array via a variable, it calls `indexOf` as expected.

I find this intriguing. Any ideas why?

### Input Code

```coffee
foo = 1

# -----------
foo in [1, 2, 3, 4, 5]

# -----------
bar = [1, 2, 3, 4, 5]
foo in bar
```

### Expected Behavior

The element presence is done via `indexOf` for inline arrays as well:

```javascript
var bar, foo,
  indexOf = [].indexOf;

foo = 1;

// -----------
indexOf.call([1, 2, 3, 4, 5], foo) >= 0;

// -----------
bar = [1, 2, 3, 4, 5];

indexOf.call(bar, foo) >= 0;
```

### Current Behavior

Demo code: [Link](https://coffeescript.org/#try:foo%20%3D%201%0A%0A%23%20-----------%0Afoo%20in%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%0A%0A%23%20-----------%0Abar%20%3D%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%0Afoo%20in%20bar%0A)

The array is transformed into a series of equality checks (regardless of the array length it seems):

```javascript
var bar, foo,
  indexOf = [].indexOf;

foo = 1;

// -----------
foo === 1 || foo === 2 || foo === 3 || foo === 4 || foo === 5;

// -----------
bar = [1, 2, 3, 4, 5];

indexOf.call(bar, foo) >= 0;
```

### Possible Solution

Call `indexOf` for inline arrays as well.

### Context

Just came across during debugging.

### Environment

* CoffeeScript version: any up to v2.6.1
* Node.js version: N/A

**Comment by vendethiel** [comment] 2022-01-17 18:14
This is an optimization. If this leads to undesirable behavior, please provide an example case we need to fix.

**Comment by GeoffreyBooth** [comment] 2022-01-17 19:44
Closing as this isn’t an issue. The output works as intended, and consistency of output is not a goal of the compiler; whereas performance is. I bet if you searched this repo you could find some discussion of this implementation years ago; my hunch is that the series of checks is more performant because it doesn’t involve first allocating memory for a new array.

**Closed by GeoffreyBooth** 2022-01-17 19:44 UTC
