### ISSUE TITLE
Feature request: void function syntax

### ISSUE THREAD

**Issue by fa7ad** [jashkenas/coffeescript#4041] opened 2015-07-20 08:35 UTC
Can we have something like say `() +>` to denote a void function?
Often I use functions as simple code blocks where return statements are redundant and sometimes can cause unexpected bugs when calling the code block. 
This becomes an issue sometimes when working with code that deals with something like jquery prototype

As a solution most of the times i have to use empty return statements in functions that would be void

So, I'd love to have a syntax specially for void functions

**Comment by vendethiel** [comment] 2015-07-20 09:12
Duplicate of #2477, also see #3731

**Closed by vendethiel** 2015-07-20 09:12 UTC
