### ISSUE TITLE
Bug: CoffeeScript doesn't respect "type":"module"

### ISSUE THREAD

**Issue by johndeighan** [jashkenas/coffeescript#5390] opened 2021-12-22 11:19 UTC
For a long time I just assumed that the problem was in node, but I was wrong. The problem is in the coffee command (probably in how it utilizes the node command). Consider the following code that I have in a file named temp.coffee:

### Input Code
```coffee
import {say} from '@jdeighan/coffee-utils'
say "Hello, World!"
```
In the same directory, I have a package.json file that includes the key "type":"module". You'll see proof of that soon. I attempt to execute this file using the command:
```text
> coffee temp.coffee
```
### Expected Behavior
Output should be:
```text
Hello, World!
```

### Current Behavior

I get this output:
```text
(node:18864) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\johnd\string-input\temp.coffee:2
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
...etc.
```
### However
if I compile the file to JS manually, then execute the resulting JS file using node with:
```text
> coffee -c temp.coffee
> node temp.js
```
I get the correct output with no errors. Note that the temp.js file has import statements, so clearly node realizes that my file is an es6 module. For reference, here is the JS file:

```javascript
// Generated by CoffeeScript 2.6.1
import {
  say
} from '@jdeighan/coffee-utils';

say("Hello, World!");
```

### Possible Solution
I don't have a possible solution. At this point, I'd be happy with a work-around. 

### Environment
```text
OS: Windows 11 (I had the same problem in Windows 10)
$ coffee -v
CoffeeScript version 2.6.1
$ node -v
v17.0.0```

**Comment by GeoffreyBooth** [comment] 2021-12-22 19:00
Duplicate of #5362. The Node `vm` module still doesn’t support ESM.

**Closed by GeoffreyBooth** 2021-12-22 19:00 UTC
