### ISSUE TITLE
Returning an object literal

### ISSUE THREAD

**Issue by vbwx** [jashkenas/coffeescript#4033] opened 2015-07-09 22:47 UTC
The following code produces a syntax error:
```coffeescript
return
    a: 1
    b: 2
```
This, however, works:
```coffeescript
return {
    a: 1
    b: 2
}
```
Syntactically, there is no reason why the braces should be mandatory.

It's just an edge case, of course, but the syntax error was unexpected ;)

**Comment by vendethiel** [comment] 2015-07-09 23:41
duplicate of #1263

**Closed by vendethiel** 2015-07-09 23:41 UTC
