### ISSUE TITLE
How to optimize coffee to generate better code?

### ISSUE THREAD

**Issue by ysmood** [jashkenas/coffeescript#3838] opened 2015-02-07 12:28 UTC
I just want to learn coffee better by altering it's source code. But I don't know which file to edit.

Such as source code:
```coffee
out = [i for i in arr]
```
It outputs:

```javascript
var i, out;

out = [
  (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      i = arr[_i];
      _results.push(i);
    }
    return _results;
  })()
];
```

I want it to output:
```javascript
var i, out;

out = [
  (function() {
    var _i, _len, _results;
    _results = new Array(arr.length); // change
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      i = arr[_i];
      _results[_i] = i; // change
    }
    return _results;
  })()
];
```

The optimized code performs nearly 70% faster in my computer: [jspref Construct array](http://jsperf.com/construct-array-of-fixed-size/2).

**Comment by lydell** [comment] 2015-02-07 13:14
Duplicate of #3693.

You're looking for src/nodes.coffee.

**Closed** 2015-02-07 13:20 UTC
Labels: duplicate
