### ISSUE TITLE
!-> define no return function, can you add this new feature?

### ISSUE THREAD

**Issue by roytan883** [jashkenas/coffeescript#4173] opened 2016-01-06 04:32 UTC
currently, if i have lots of no return functions, i need manually add an empty line 'return' to force coffee not compile return line to javascript code. 
```
testFunc = ->
  for i in [1..5]
    execSomething i
  return
```
with empty return, the js code looks good
```
testFunc = function() {
  var i, j;
  for (i = j = 1; j <= 5; i = ++j) {
    execSomething(i);
  }
};
```
but if i dont add 'empty return' at the end of func
```
testFunc = ->
  for i in [1..5]
    execSomething i
```
it will create a 'results' object, it is waste, and the code looks no i wanted. 
Also when some callback func nested, if no 'empty return', lots of  'results' object, much horrible.
```
testFunc = function() {
  var i, j, results;
  results = [];
  for (i = j = 1; j <= 5; i = ++j) {
    results.push(execSomething(i));
  }
  return results;
};
```
In livescript, i can create no return function by simplely define a function with !-> that means no return value; -> just like coffeescript, auto return the last variable
 (webstrom livescript plugin can't highlight code, so i try to use coffee, it's plugin work much better )
the !-> works just i wanted:
```
testFunc = !->
  for i in [1..5]
    execSomething i
```
compile to
```
testFunc = function() {
  var i, j;
  for (i = j = 1; j <= 5; i = ++j) {
    execSomething(i);
  }
};
```
especially, in nodejs, have lots of nested callback functions, 99% of them are no return function, !-> can solve this problem.

**Comment by vendethiel** [comment] 2016-01-06 21:31
duplicate of #2477 and its brothers

**Closed by vendethiel** 2016-01-06 21:31 UTC

**Comment by roytan883** [comment] 2016-01-07 05:39
have u wrote nodejs node? do you know 99% callback functions are no return function ??? 
if i brother u, can u give a suggestion solve the problem？ I hate writing the no sense return

**Comment by connec** [comment] 2016-01-07 12:25
In coffee script it is not a "no sense" return, and there is no such thing as a "no return" function.  All functions return the result of their final expression, so the final expression should be what you want to return.

If you want to indicate that the function has no meaningful return value, an empty `return`, `null`, or `undefined` as the final expression will convey this.

**Comment by roytan883** [comment] 2016-01-08 03:23
Always write “return, null, or undefined as the final expression” at nested callback loop in nodejs is painfull ! 
Nodejs user know what i mean

**Comment by carlsmith** [comment] 2016-01-08 03:40
Personally, I see that as a problem with Node users. If people insist on using the wrong language for the task, just because they love that language, then callback hell is exactly the type of problem they create for themselves. I know that isn't going to be a popular view, but it is about time people stopped trying to make a bad idea work, and started using a language with threads to write servers.

**Comment by bjmiller** [comment] 2016-01-08 06:12
I'm not sure if you realize this, but it generally doesn't matter what the return value of a callback function is in Node.  It's there for the side effects, and is usually thrown away.

For those rare occasions where an API that someone wrote cares what you return, you can put a `return` statement at the end of a function, to explicitly return undefined.  Explicit is better than implicit, after all.  But, you don't have to bother with it in most, if not all, of Node's builtins.

**Comment by roytan883** [comment] 2016-01-08 06:20
I think nodejs isn't bad language, even coffeescript is installed by nodejs npm :)

Also nodejs has some good library to solve the "callback hell" problem, like "async" which can make nested callback functions parallel. But, still, lots of callback functions are exist  although they are not nested, but they are everywhere in nodejs world. That's why i think use coffeescript implicitly return in nodejs is painful.

if !-> can simplely forbid implicitly return, why its unacceptable? Livescipt already has it, and it works great. It is not conflict with current coffeescipt code, treat !-> as advanced function definition. So its unacceptable is caused by technical or personal (although it is good, by still must not support it, just because another xxxScript already has it) ? 

Or the author think: hey, nodejs user, do not use callback function when your are using coffeescipt (coffeescipt believe most function need return value, you nodejs guys are minority because you use callback function). 
Then the nodejs user will think: well, how should i write nodejs code without callback functions?

Again, if coffeescipt think nodejs is wrong language for coffeescipt usage, why itself depend on nodejs's NPM? That is funny !!!

Once again: 99.9% of nodejs callback function DO NOT need return value! 
Why i need write  Explicit “return, null, or undefined as the final expression” in those 99.9% callback functions ?

**Comment by roytan883** [comment] 2016-01-08 06:30
@bjmiller I know that nodejs doesn't care the return value. But the problem is coffeesciprt generated javascipt code is bad, it implicitly create 'result' object and push unused data in to it. In server side program, it is a big waste of performance if you not use Explicit “return, null, or undefined as the final expression” to forbid the coffeescipt default implicitly return.

**Comment by roytan883** [comment] 2016-01-08 06:40
" Explicit is better than implicit " I agree that. 
So at the beginning of function use !-> explicit define no return value function, is it more Explicit ?

when you use other library or API, you just read the function header, you already know it has return or no return value, it that better than you read the whole function code?

**Comment by carlsmith** [comment] 2016-01-08 10:40
Just for clarity. I'm not CoffeeDev. My view is not representative of this community either. I just *personally* think Node is the inverse of Brython, and saw that as relevant here.
