### ISSUE TITLE
ES 2017 #private class fields

### ISSUE THREAD

**Issue by MegaJSDeveloper** [jashkenas/coffeescript#5281] opened 2019-12-30 21:51 UTC
CoffeeScript:
```coffeescript
class Cat
  
  constructor: ->
    @@name = 33
    return
    
  say: ->
    return @@name
```

Must compile to:
```javascript
class Cat {
	#name
	
	constructor(){
		#name = 11
	}
	
	say(){
		return this.#name
	}

}
```

**Comment by GeoffreyBooth** [comment] 2019-12-30 22:00
Duplicate of https://github.com/jashkenas/coffeescript/issues/4552.

**Closed by GeoffreyBooth** 2019-12-30 22:00 UTC
