### ISSUE TITLE
Feature: Reverse existential assignment

### ISSUE THREAD

**Issue by Aldlevine** [jashkenas/coffeescript#4047] opened 2015-07-24 17:02 UTC
Instead of writing:

```coffeescript
@a = b ? @a
```

It would be great to have something like a reverse existential assignment.

```coffeescript
@a =? b
```

This would be great for situations where you have a class/object with default properties and you'd like to assign other properties over the defaults if they exist, otherwise leave the defaults.

Thoughts?

**Comment by lydell** [comment] 2015-07-24 18:42
Duplicate of #3997.

**Comment by Aldlevine** [comment] 2015-07-24 19:05
@lydell Thanks, I looked but I couldn't find this idea referenced. Too many closed issues to sort through.

**Closed** 2015-07-24 19:46 UTC
