### ISSUE TITLE
Postinstall script fails on Windows PowerShell, affects installs of non-CoffeeScript projects

### ISSUE THREAD

**Issue by 4O4** [jashkenas/coffeescript#4806] opened 2017-11-30 08:42 UTC
Hello, I don't use CoffeeScript at all but I ended up writing this issue after wasting some time on debugging why am I suddenly unable to do a successfull `npm install` on my TypeScript project. I work on win10 machine and use Windows Powershell as primary terminal for node and npm related stuff. Version info:

```
> node --version
v9.2.0          
> npm --version 
5.5.1           
```

Error details:

```
> coffee-script@1.12.8 postinstall C:\my-project\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:452:27)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:598:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This is caused by the recently merged PR #4759. The `node --eval ...` script / command is not compatible with powershell. It is a huge issue for me, becase as I said before - I'm not even a direct user of CoffeeScript. Some of my dependencies (or dependencies of dependencies) must be using it.

**Comment by ntbnnt** [comment] 2017-11-30 08:59
Thanks for opening this issue - I just ran into this issue as well!

**Comment by Lars-Kristian** [comment] 2017-11-30 09:01
I also got this issue.

**Comment by siiron** [comment] 2017-11-30 09:04
**+1**

I'm also on Windows 10, node v8.9.1 and npm 5.5.1, using cmdr for my main terminal, but the issue is also caused using native cmd on windows.

Not using coffee-script/ coffeescript directly but it is installed through sub-dependencies.
I get an identical error, and currently it's breaking everything. Major foobar :-(

**Comment by vendethiel** [comment] 2017-11-30 09:09
Duplicate of #4805

**Closed by vendethiel** 2017-11-30 09:09 UTC
