### ISSUE TITLE
`unexpected newline` when multiline comment in array

### ISSUE THREAD

**Issue by YamiOdymel** [jashkenas/coffeescript#4460] opened 2017-03-09 13:53 UTC
`coffeescript@2.0.0-alpha1` _(the same error also occurred with [js2.coffee](http://js2.coffee/))_

```coffee
a = [
  ###
  User
  ###
  {
      username: "YamiOdymel"
  }
]
```

`output`

```bash
[stdin]:4:6: error: unexpected newline
  ###
     ^
```

---

```coffee
a = [
  ###
  {
      username: "YamiOdymel"
  }
  ###
]
```

`output`

```bash
[stdin]:6:5: error: unexpected indentation
  ###
    ^
```

**Comment by vendethiel** [comment] 2017-03-09 14:14
CoffeeScript doesn't try its hardest to preserve comments.

Duplicate of #4290.

**Closed by vendethiel** 2017-03-09 14:14 UTC
