### ISSUE TITLE
Interpolated keys in object literals don't work in all cases

### ISSUE THREAD

**Issue by bcherny** [jashkenas/coffeescript#3963] opened 2015-04-29 17:30 UTC
Introduced in https://github.com/jashkenas/coffeescript/commit/76c076db555c9ac7c325c3b285cd74644a9bf0d2

**ok:**

```coffee
foo {
  "#{ 1 + 2 }": 3
}

// or equivalently:
foo (
  "#{ 1 + 2 }": 3
)

// or:

foo "#{ 1 + 2 }": 3
```
=>
```js
var obj;

foo((
  obj = {},
  obj["" + (1 + 2)] = 3,
  obj
));
```

**not ok:**

```coffee
foo
  "#{ 1 + 2 }": 3
```
=>
```
Error on line 2: unexpected indentation
```

**Comment by lydell** [comment] 2015-04-29 18:07
Duplicate of #3935.

**Closed** 2015-04-29 19:41 UTC
Labels: duplicate

**Comment by bcherny** [comment] 2015-04-29 21:20
ha, beat me to it :)
