### ISSUE TITLE
coffee1.9 compile to js 

### ISSUE THREAD

**Issue by yanzou** [jashkenas/coffeescript#3817] opened 2015-01-30 08:26 UTC
```coffee
 constructor:(@name, @params={}) ->
    super name, params
    @_isHeaderRead = false
    @_tableHeadersPosition = []

```

after complie (in coffee -v 1.9.0)
```
  function TableSection(_at_name, _at_params) {
    this.name = _at_name;
    this.params = _at_params != null ? _at_params : {};
    TableSection.__super__.constructor.call(this, name, params);//sould be _at_name, _at_params ?
    
```

**Comment by Santinell** [comment] 2015-01-30 09:41
no vars "name" and "params" in context. only "@name" and "@params"
so use @name and @params

**Comment by yanzou** [comment] 2015-01-30 10:14
yeah I aware of that, 
so that means I have to modify lots of our (company's) code...  OMG

**Comment by NicholasBoll** [comment] 2015-01-31 00:45
I ran into this as well using AngularJS. I'm assuming more people will run into this problem as dependencies get updated (npm update). AngularJS uses `Function.prototype.toString` to annotate dependencies.

After this change, those variables get munged and Angular's injector cannot find dependencies.

I agree that ideally this should not be a problem, but in reality it is. AngularJS is not the only DI library to use this trick to inject dependencies based on variable names.

**Comment by vendethiel** [comment] 2015-01-31 00:54
> I agree that ideally this should not be a problem, but in reality it is. AngularJS is not the only DI library to use this trick to inject dependencies based on variable names.

Most production angular apps use explicit DI instead, though ;-).

**Comment by NicholasBoll** [comment] 2015-01-31 01:23
Explicit DI usually means something like ng-annotate which usually isn't usually run during the develop step because it takes much longer (uses AST). ng-annotate also doesn't work well with CS classes that use constructors at injection point (the future of Angular).

My argument is not against idealism, but rooted in reality.

**Comment by NicholasBoll** [comment] 2015-02-01 04:39
I spent a few hours getting ngAnnotate to work with an Angular repository that uses CoffeeScript classes. Since ngAnnotate works with the transpiled JavaScript, the `$inject` array contains the `_at_` as well: `foo.$inject = ["_at_$scope"]`. Not ideal.

**Comment by epidemian** [comment] 2015-02-02 19:50
Hmm. It seems that relying on this non-documented (and buggy) behaviour was quite common:

```coffeescript
class Person
  constructor: (@name) ->
    @greeting = "Hi, i'm #{name}" # Assume auto-gen "name" local variable exists.
```

Could we perchance go back to 1.8 behaviour, detect these cases, and warn about them relying on an implementation bug and that they will stop working on a future version (say, 1.10)? 

/cc @jashkenas, @lydell

**Comment by jashkenas** [comment] 2015-02-02 19:57
This is a duplicate of #3816

**Closed by jashkenas** 2015-02-02 19:57 UTC
