### ISSUE TITLE
An object key shouldn't need to be declared before an assignment that specifies it.

### ISSUE THREAD

**Issue by fernandortdias** [jashkenas/coffeescript#5339] opened 2020-12-23 23:16 UTC
Feature request

### Input Code

```coffee
a.b.c.d = 10 
alert("a.b.c.d = " + a.b.c.d)

```

### Expected Behavior

a.b.c.d = 10

### Current Behavior

error;

### Possible Solution

var a;

if (typeof a === "undefined" || a === null) {
  a = {};
}

if (a['b'] == null) {
  a['b'] = {};
}

if (a['b']['c'] == null) {
  a['b']['c'] = {};
}

if (a['b']['c']['d'] == null) {
  a['b']['c']['d'] = {};
}

a.b.c.d = 10;

alert("a.b.c.d = " + a.b.c.d);

### Context

As Coffeescript doesn't require variables do be declared before assigning values to them, I'd expect that a missing key in a object hadn't to be declared either before an assignment to that key. This way it would be much easier to represent a sparse matrices as objects.

I've got the "possible solution" above using this code in CoffeeScript:

a = {} unless a? 
a['b'] = {} unless a['b']? 
a['b']['c'] = {} unless a['b']['c']? 
a['b']['c']['d'] = {} unless a['b']['c']['d']? 

a.b.c.d = 10 

alert("a.b.c.d = " + a.b.c.d)

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: N/A

**Comment by edemaine** [comment] 2020-12-23 23:54
The canonical solution to this is
```coffee
a ?= {}
a.b ?= {}
a.b.c ?= {}
a.b.c.d = 10
```

Are you suggesting that `a.b = 5` should automatically prepend `a ?= {}`? This seems likely dangerous and bad, as it's using JavaScript notation with a very non-JavaScript meaning.

I could imagine a different operator like `a!.b = 5` (or some other notation) that automatically does `a ?= {}` before `a.b = 5`, though.

**Comment by vendethiel** [comment] 2020-12-24 12:47
Duplicate of #2610, #1870, #1642, #1394, and somewhat #1141 & #881.

**Closed by vendethiel** 2020-12-24 12:47 UTC
