### ISSUE TITLE
Bug: Wrong line number is reported from jest tests

### ISSUE THREAD

**Issue by dima4p** [jashkenas/coffeescript#5338] opened 2020-11-26 20:43 UTC
Bug report

### Input Code

[Source of the test project](https://github.com/dima4p/JS-test)

#### Wrong line number in coffeescript

1. Clone the repo

2. `cd` to the cloned directory

3. `yarn install --check-files`

4. `yarn test`

5. You will see, that test failed at `spec/javascript/models/sample_spec.coffee:46:42` while there is only 36 lines in the file.

### Expected Behavior

You sholud see, that test failed at `spec/javascript/models/sample_spec.coffee:33:42`

### Current Behavior

You see, that test failed at `spec/javascript/models/sample_spec.coffee:46:42` while there is only 36 lines in the file.
 
If you remove all the lines started with `set`, the line number will be reported correctly.

### Environment

* CoffeeScript version: 2.5.1
* Node.js version: v12.18.0.

**Comment by vendethiel** [comment] 2020-11-26 22:42
Duplicate of #5337.

**Closed by vendethiel** 2020-11-26 22:42 UTC

**Comment by dima4p** [comment] 2020-11-27 07:07
> Duplicate of #5337.

#5337 is not solved!!!

**Comment by GeoffreyBooth** [comment] 2020-11-28 02:26
Please provide a reproduction that demonstrates the bug in less than 100 lines of code.

You're asking someone to donate their time to fix this bug. Part of the bargain is that you make their job as easy as possible—ideally you attempt to fix the bug yourself and post a PR. If you can't, for whatever reason, at least do as much as you can to minimize the volunteer effort.

**Comment by dima4p** [comment] 2020-11-28 07:07
> Please provide a reproduction that demonstrates the bug in less than 100 lines of code.
> 
> You're asking someone to donate their time to fix this bug. Part of the bargain is that you make their job as easy as possible—ideally you attempt to fix the bug yourself and post a PR. If you can't, for whatever reason, at least do as much as you can to minimize the volunteer effort.

The code, that demonstrate the bug is only 36 lines long.
