### ISSUE TITLE
Possible bug with dot at beginning of line, ternary and object

### ISSUE THREAD

**Issue by tremby** [jashkenas/coffeescript#4150] opened 2015-11-25 01:35 UTC
1.7.0 added "Leading . now closes all open calls, allowing for simpler chaining syntax."

This is great, but I may have just stumbled on a bug with that when using the ternary operator and an object argument.

``` coffee
gulp.task 'stylus', ->
    gulp.src [
        './src/stylus/vars.styl'
        './src/stylus/**/*.styl'
    ]
        .pipe if argv.sourcemaps then require('gulp-sourcemaps').init() else gutil.noop()
        .pipe require('gulp-concat') 'styles.styl'
        .pipe require('gulp-stylus')
            use: require('nib')()
        .pipe if isLocal() then gutil.noop() else require('gulp-minify-css')
            compatibility: '' # Empty string is IE9+ (this is default)
        .pipe if argv.sourcemaps then require('gulp-sourcemaps').write() else gutil.noop()
        .pipe gulp.dest './dist/css'
```

This is coming out as

``` js
// Generated by CoffeeScript 1.9.2
gulp.task('stylus', function() {
  return gulp.src(['./src/stylus/vars.styl', './src/stylus/**/*.styl']).pipe(argv.sourcemaps ? require('gulp-sourcemaps').init() : gutil.noop()).pipe(require('gulp-concat')('styles.styl')).pipe(require('gulp-stylus')({
    use: require('nib')()
  })).pipe(isLocal() ? gutil.noop() : require('gulp-minify-css')({
    compatilibilty: ''
  }).pipe(argv.sourcemaps ? require('gulp-sourcemaps').write() : gutil.noop())).pipe(gulp.dest('./dist/css'));
});
```

I was expecting
- `compatibility: ''` object to be an argument to `require('gulp-minify-css')` -- in this case the result is as expected.
- the dot at the start of the next line to close both the ternary and the `pipe()` from the preceding line -- in this case the result is not as expected: the next `.pipe()` is chained on the end of the `gulp-minify-css` object.

Note that the `gulp-stylus` pipe above also receives an object as an argument but does not have a ternary. This one compiles as I expect.

Note also that the `gulp-sourcemaps` pipes have ternaries but no object argument, and these ones also compile as I expect.

So it seems it's a combination of the tenary and the object argument on a new line.

Is this a bug or am I understanding something incorrectly?

**Comment by GeoffreyBooth** [comment] 2017-04-23 21:47
There are many ways to confuse the compiler with leading periods. Please use parentheses to make your intentions clear:

```coffee
gulp.task 'stylus', ->
    gulp.src([
        './src/stylus/vars.styl'
        './src/stylus/**/*.styl'
    ])
    .pipe if argv.sourcemaps then require('gulp-sourcemaps').init() else gutil.noop()
    .pipe require('gulp-concat') 'styles.styl'
    .pipe(require('gulp-stylus')(
        use: require('nib')())
    ).pipe(if isLocal() then gutil.noop() else require('gulp-minify-css')
        compatibility: '' # Empty string is IE9+ (this is default)
    ).pipe if argv.sourcemaps then require('gulp-sourcemaps').write() else gutil.noop()
    .pipe gulp.dest './dist/css'
```

**Comment by tremby** [comment] 2017-04-23 22:21
That's a shame. What's the point in the feature if you can't use it? Or what's the rule on when it can be used and when it can't?

**Comment by GeoffreyBooth** [comment] 2017-04-23 22:36
It works well when there aren’t indented lines inside the chaining (`use` and `compatibility` in your case). Those seem to confuse the compiler. Perhaps there is a way to disambiguate those, but I get the sense that there isn’t, because this has come up many times before. We probably should’ve disallowed leading period chaining in such scenarios, but it’s been around for so long now that doing so would break lots of code. If I’m wrong and there is a way to make the compiler do what you want, please submit a PR and I’d be happy to accept it.

It’s similar to how sometimes parentheses are required for function calls, for example if you have other code afterward on the same line. When you chain like this, you’re really creating one long line of code; so sometimes parentheses are required to disambiguate.

So to answer your question: use chaining when each line starts with a period. If you need a multiline block in one of the parts of the chain, wrap that block in parentheses (like I did for `gulp-stylus` above).

**Comment by connec** [comment] 2017-04-24 10:29
> So it seems it's a combination of the tenary and the object argument on a new line.

I agree. Perhaps the logic for closing implicit calls for leading `.`s won't continue through ternaries?

**Comment by tremby** [comment] 2017-04-24 17:27
Would it help (and make sense? it would to me) to interpret deeper indentation on a following line as a continuation, versus equal (or lesser) indentation as the end of the preceding function call?

**Comment by GeoffreyBooth** [comment] 2017-04-24 17:33
Chaining is supposed to be unindented:

```coffee
$('#button')
.show()
.hide()
.css('color', 'red')
.show()
```

Which is why it was surprising that your example worked at all.

**Comment by tremby** [comment] 2017-04-24 17:43
Does it actually make a difference to the parser at present? If the next line is starting with a `.`, and is at the same indentation level, or deeper, is there any difference in the interpretation?

I always presumed not, and liked to indent chaining lines as an extra visual clue that they are a continuation of something earlier. But I have no problem changing the way I write if it would disambiguate and help in keeping code and diffs terse (read: fewer parens).

So perhaps the code example in this thread should now be this:

```coffee
gulp.task 'stylus', ->
    gulp.src [
        './src/stylus/vars.styl'
        './src/stylus/**/*.styl'
    ]
    .pipe if argv.sourcemaps then require('gulp-sourcemaps').init() else gutil.noop()
    .pipe require('gulp-concat') 'styles.styl'
    .pipe require('gulp-stylus')
        use: require('nib')()
    .pipe if isLocal() then gutil.noop() else require('gulp-minify-css')
        compatibility: '' # Empty string is IE9+ (this is default)
    .pipe if argv.sourcemaps then require('gulp-sourcemaps').write() else gutil.noop()
    .pipe gulp.dest './dist/css'
```

**Comment by lydell** [comment] 2017-04-24 17:45
> Chaining is supposed to be unindented

I've never heard about chaining being "supposed" to be in any particular way. All CoffeeScript I've ever written has used _indented_ chaining (because that's what I'm used to from JavaScript). I don't think anyone knows the exact rules. What makes things harder is that the compiler has always been a little too permissive and since CoffeeScript has been around for so long now, it's hard to tell intended behavior from accidental. CoffeeScriptRedux tried to define sane rules for stuff like this, but people have come to depend on accidental quirks (which is one reason people sadly had problems adopting CSR).

**Comment by jashkenas** [comment] 2017-04-24 17:51
Chaining like this was not supposed to be supported in the first place. Originally, a leading `.` on a subsequent line was supposed to to connect to the immediately preceding expression — no closing of implicit parens or braces, period. The point was to avoid the ambiguities.

But that got changed when the PR got merged years ago.

**Comment by GeoffreyBooth** [comment] 2017-04-24 17:53
Well that’s what happens when we don’t document a feature 😄

Its only documentation is in the changelog for 1.7.0: http://coffeescript.org/v2/#1.7.0, and there it’s unindented. I had always assumed the unindentation was intentional, since indentation implies a new block, and chaining most emphatically is _not_ a new block—it’s really a single line of code. But clearly the compiler allows either.

We could fix this as part of the breaking changes for 2, but I don’t think we really gain anything other than intellectual cohesiveness, at the expense of lots of people needing to revise their code for no real reason.

**Comment by tremby** [comment] 2017-04-24 18:00
But would it help in the context of this thread? Could it make it clear to the compiler what my intended meaning was? See the "I expected" list from my original post.

I am increasingly getting the impression that this indentation conversation is actually not relevant to the bug(?) I was pointing out. I think the real issue is that there's something awry when a ternary and object argument are given as part of chains. The dot at the start of the line is supposed to close all preceding function calls, and in this case this is not happening.

**Comment by GeoffreyBooth** [comment] 2017-04-27 04:34
Related: #3866.

**Comment by GeoffreyBooth** [comment] 2017-05-01 07:07
Here’s a minimal example:

```coffee
a
.b if yes then 1 else c
  d: 1
.e()
```

[currently compiles to](http://localhost/v2/#try:a%0A.b%20if%20yes%20then%201%20else%20c%0A%20%20d%3A%201%0A.e()):

```js
a.b(true ? 1 : c({
  d: 1
}).e());
```

should compile to:

```js
a.b(true ? 1 : c({
  d: 1
})).e();
```

**Comment by xixixao** [comment] 2017-05-01 15:59
This is a bug, and should work regardless of indentation (I would prefer to enforce that the chain call be indented, but I guess a lot of ppl don't indent, including @GeoffreyBooth ).

As the documentation says:
> Leading . now closes all open calls, allowing for simpler chaining syntax.

And clearly `.b` above is an open call.

I would guess that #3866 is a separate issue.

**Comment by GeoffreyBooth** [comment] 2017-05-01 17:35
@xixixao When the feature was introduced, its only documentation was in the [changelog](http://coffeescript.org/v2/#changelog) (for 1.7.0) and that example didn’t indent. I assumed therefore that that was the only possible syntax, and that indentation would be invalid (as indentation implies a new block, but chaining is really a continuation of the previous line, certainly not a new block).

At this point we’re stuck supporting both variants, since there’s a lot of code out there that uses one or the other style; but based on the documentation and the general meaning of indentation, the non-indented style _should_ be the only accepted variant; or at least the default variant for purposes of documentation and testing.

**Comment by xixixao** [comment] 2017-05-01 17:46
@GeoffreyBooth Yeah, I have no clue why I didn't indent that example (I have a hunch I took it over from somewhere, but I might be completely wrong). Maybe I'm skewed by over a year of writing in ES6, but I would definitely encourage everyone to indent the method calls (i.e. we should change that example).

**Comment by GeoffreyBooth** [comment] 2017-05-01 18:01
Again, we’re stuck supporting both styles now. But I think the example in the docs should stay as it is (and move into the regular documentation, not just in the changelog). Indentation in CoffeeScript represents a new block; indenting something and _not_ having a new block form generally should throw an `unexpected indentation` error from the compiler. It’s way too late to fix that now for this feature, but if we were being intellectually coherent that’s how it should’ve behaved back when it was introduced.

I understand that the indented style looks better, and that’s why it’s popular in JavaScript; but we have significant indentations here.

**Closed** 2017-05-03 06:00 UTC
