### ISSUE TITLE
[CS2] Immediate instantiation of named class

### ISSUE THREAD

**Issue by helixbass** [jashkenas/coffeescript#4567] opened 2017-06-11 04:08 UTC
Ran into this while working on #4561:

`x = new class A` compiles to `x = new (A = )class A {};`

This appears to be a result of the dummy `Assign` to `''` being concatenated to the compiled class body inside `Class#compile_node`

**Comment by vendethiel** [comment] 2017-06-11 08:06
Dupe of #4436.

**Closed by vendethiel** 2017-06-11 08:06 UTC
