### ISSUE TITLE
Grammar: Inline function without parentheses used as `if` condition fails to compile

### ISSUE THREAD

**Issue by provegard** [jashkenas/coffeescript#3921] opened 2015-03-29 17:47 UTC
If I enter the following code on coffeescript.org:

```
ids = [1, 2]
test = "2"
if ids.some (id) -> id.toString() == test
  alert "yes"
```

...I get "Error on line 3: unexpected if"

How come?

Any of the following variations removes the error:

```
if (ids.some ((id) -> id.toString() == test))
if ids.some (((id) -> id.toString() == test))
if ids.some(((id) -> id.toString() == test))
```

**Comment by vendethiel** [comment] 2015-03-29 17:56
The body is considered to be part of the function, not the `if`.

**Comment by epidemian** [comment] 2015-03-29 19:22
> The body is considered to be part of the function, not the if.

Are you sure that's the case? Because:

```coffeescript
ids.some (id) -> id.toString() == test
  alert "yes"
```

*Also* fails to compile, with `Error on line 2: unexpected indentation`.

I find this second error quite intuitive: the indented `alert "yes"` doesn't make sense there, as the `(id) ->` function defines its body on the rhs od the arrow instead of an indented block. But it *could* make sense in the OP code, as the body of the `if` expression. Don't you think so?

**Comment by vendethiel** [comment] 2015-03-29 19:49
It took me a while to find it... #2555.
It seems I got confused by [this comment](https://github.com/jashkenas/coffeescript/issues/2555#issuecomment-13018170), and it even seems the commit closing it doesn't support @satyr's comment there.

**Comment by adamdanielsdesign** [comment] 2015-04-02 21:04
@provegard this seems like this would need to be an additional syntax as a one-liner:
```
#example
ids = [1, 2]
test = "2"
id = 2
alert "yes" if ids.some (id) -> id.toString() == test
```

**Comment by adamdanielsdesign** [comment] 2015-04-02 21:08
basically you're mixing literate syntax with standard condition-statement syntax

**Comment by provegard** [comment] 2015-04-05 20:52
@adamdanielsdesign That's another workaround, but as the body of a function cannot both occur to the right hand side of the arrow and as an indented block, why does my original code fail to compile?

**Comment by adamdanielsdesign** [comment] 2015-04-05 22:45
@provegard 
```
#try
ids = [1, 2]
test = "2"
id = 2
idMatch = ->
  ids.some (id)-> id.toString() == test
#this style must evaluate to the compiler as a condition only ie (true) works, but not ' (id) -> #somestatement'
if idMatch
  alert "yes"
```
The answer pretty sure is that the compiler needs to have method of knowing if you're running a function or a conditional.  Currently if it reads '->' it breaks out of literate style syntax and expects proper function structure.

**Comment by adamdanielsdesign** [comment] 2015-04-05 22:54
@provegard Also, you said that 
```
ids = [1, 2]
test = "2"
id = 2
alert "yes" if ids.some (id) -> id.toString() == test
```
is a work around, is there another more verbose example? because
```
#this works for more complex statements
ids = [1, 2]
test = "2"
(if true || somecondition
  alert 'yes'
)if ids.some (id) -> id.toString() == test
```

**Comment by GeoffreyBooth** [comment] 2017-05-06 06:11
I’m not sure what the issue is here. The line in question seems ambiguous:
```coffee
if ids.some (id) -> id.toString() is test
# How does the compiler know whether this is:
if (ids.some (id) -> id.toString()) is test
# Or if it’s:
if (ids.some (id) -> id.toString() is test)
```
The `is test` could be part of the body of the function, or part of the conditional. I’m not sure how the compiler could be able to compile this.

**Comment by connec** [comment] 2017-05-06 11:29
I think the actual issue is do to with the `if` not compiling when the condition does:

```coffee
ids.some (id) -> id.toString() is test
```

Compiles just fine to:

```js
ids.some(function(id) {
  return id.toString() === test;
});
```

But `if ...` will not compile. I think this must be CS failing to disambiguate the indented block from being the function body or the `if` body. In this case I would expect it to be the `if` body since the function body is inline.

As identified in the 1st post, the current workaround would be to put the function into parens.

```coffee
if (ids.some (id) -> id.toString() == test)
  alert "yes"
```

**Comment by Inve1951** [comment] 2017-12-26 07:49
I just ran into the same issue. here's a [minimal example](http://coffeescript.org/v2/#try:if%20func%20-%3E%20true%0A%20%20%22compiles%3F%22%0A):
```coffee
if func -> true
  "compiles?"
```
```
[stdin]:1:1: error: unexpected if
if func -> true
^^
```

@GeoffreyBooth pinging you since this is rather old and you are the one who closed without action.

**Comment by vendethiel** [comment] 2017-12-26 11:13
Also serms like the example used to close this issue isn't actually ambiguous.

**Comment by Inve1951** [comment] 2018-01-04 09:51
found [something similar](http://coffeescript.org/v2/#try:for%20a%20in%20do%20-%3E%20b%0A%20%20a%0A) that seems related:
```coffee
for a in do -> b
  a

[stdin]:2:1: error: unexpected indentation
  a
^^
```

**Closed** 2018-01-29 01:51 UTC
Labels: bug
