### ISSUE TITLE
error output of '@' in constructor's parameter

### ISSUE THREAD

**Issue by plrthink** [jashkenas/coffeescript#3839] opened 2015-02-07 13:23 UTC
I'm using coffeescript v1.9.0 on my mac with node v0.11.13 and npm v.1.4.9.

the output of 

    class AppController
      constructor: (@$mdSidenav) ->

would become 
  
    AppController = (function() {
        function AppController(_at_$mdSidenav) {
           this.$mdSidenav = $mdSidenav;
        }
        return AppController;
    })();

whose parameter `@$mdSidenav` become `_at_mdSidenav` cause angular $injector can't find the correct service to inject to. 

It didn't go wrong with v1.8.0.

**Comment by lydell** [comment] 2015-02-07 13:34
Duplicate of #3816.

**Comment by vendethiel** [comment] 2015-02-07 13:34
@lydell Now that's what I call being swift...

**Closed by lydell** 2015-02-07 13:34 UTC
