### ISSUE TITLE
implicitly return is so stupid, give the choose to user.

### ISSUE THREAD

**Issue by 1987zfp** [jashkenas/coffeescript#4667] opened 2017-08-30 01:02 UTC
don't restrict culture

if your app has much void function, like web,
you must add return; to every last line, that's so ugly.
explicitly return is better

otherwise, bla, bla, bla

convenient is the best
please use ^-> or other  syntax to add return; auto

**Comment by GeoffreyBooth** [comment] 2017-08-30 01:58
Duplicate of #2477, #2726, #2923, #3731, #3762, #4041, #4173, #4210.

Please don’t open duplicate issues. This question is settled.

**Closed by GeoffreyBooth** 2017-08-30 01:58 UTC
