### ISSUE TITLE
switch interferes with "break" even though "break" not needed in switch

### ISSUE THREAD

**Issue by shaunc** [jashkenas/coffeescript#3920] opened 2015-03-28 05:24 UTC
I understand that "break" is not used to stop passing from one "when" of a switch statement to the next in coffeescript. This means, I would expect, that break in a switch should break out of a loop surrounding the switch, yet it doesn't:

    while true
      console.log('loop')
      switch 1
        when 1
          break

Prints "loop" forever.

**Comment by lydell** [comment] 2015-03-28 10:00
Duplicate of #2833.

**Closed** 2015-03-28 10:03 UTC
