### ISSUE TITLE
New _at_ argument syntax breaks Angular

### ISSUE THREAD

**Issue by bioball** [jashkenas/coffeescript#3836] opened 2015-02-07 03:03 UTC
Angular parses the name of the arguments passed into a function, so until the release of 1.9, it was pretty great for me to do this style of coding:

```coffeescript
inject (@$rootScope, @foo, @baz) ->
```

Which compiled into:

```js
inject(function($rootScope, foo, baz){
  this.$rootScope = $rootScope;
  this.foo = foo;
  this.baz = baz;
});
```

With 1.9.0, this now compiles into:

```js
inject(function(_at_$rootScope, _at_foo, _at_baz) {
  this.$rootScope = _at_$rootScope;
  this.foo = _at_foo;
  this.baz = _at_baz;
});
```

Given that the name of the variable changed, Angular now throws this kind of error:

```bash
    Error: [$injector:unpr] Unknown provider: _at_fooProvider <- _at_foo
    http://errors.angularjs.org/1.3.12/$injector/unpr?p0=_at_fooProvider%20%3C-%20_at_foo
```

What's the reasoning behind this change? It's one less piece of syntactic sugar we have available, that made writing Angular, especially unit tests, really really nice.

**Comment by michaelficarra** [comment] 2015-02-07 03:27
Duplicate of #3816.

**Closed by michaelficarra** 2015-02-07 03:27 UTC
