### ISSUE TITLE
incorrect sourcemap file path in 1.6.2

### ISSUE THREAD

**Issue by mark-hahn** [jashkenas/coffeescript#2882] opened 2013-03-24 22:55 UTC
I'm seeing an incorrect path in 1.6.2. I'm using chrome Version 26.0.1410.40 beta-m.  

This just started happening today and Friday it worked fined with my same source code and same version of coffeescript. I just tried switching from Chrome stable to beta (see version above) but it made no difference.

The correct file path should be `/ri/src/pages/js/client_helpers.cof` but I'm getting `/ri/src/src/pages/js/client_helpers.cof` from chrome to my server.

The sourcemap says ....

```
 "version": 3,
  "file": "proj_metadata_client.js",
  "sourceRoot": "../../../../..",
  "sources": [
    "src/pages/main/stage/stage_hdr/proj_metadata_client.cof"
  ],
```

I can patch the map to work by changing `"../../../../.."` to `"../../../../../.."` or by removing `src/` from the `sources` property.

**Comment by GeoffreyBooth** [comment] 2017-04-30 08:27
Looks like a duplicate of #3296 (I know, it came later, but it’s better documented). Even if this isn’t a duplicate, any fix of that issue should fix this as well.

**Closed by GeoffreyBooth** 2017-04-30 08:27 UTC
Labels: bug, duplicate
