### ISSUE TITLE
Compilation errors when returning objects from functions

### ISSUE THREAD

**Issue by ghost** [jashkenas/coffeescript#1796] opened 2011-10-23 22:35 UTC
PARSE ERROR ON LINE 3: UNEXPECTED 'INDENT'

``` coffee
class Test
    @get: ->
        return
             x: 1
             y: 2
```

Seems like return doesn't mix with no-commas/no-braces approach.

**Comment by hakatashi** [comment] 2015-06-13 11:36
`throw` has this syntax already. Why shouldn't `return` to have?

```coffeescript
throw
  x: 1
  y: 2

# throw {
#   x: 1,
#   y: 2
# };
```

**Comment by GeoffreyBooth** [comment] 2017-04-29 04:03
Duplicate of #1263.

**Closed by GeoffreyBooth** 2017-04-29 04:03 UTC
Labels: change
