### ISSUE TITLE
`+=` does not declare variables

### ISSUE THREAD

**Issue by alfgaar** [jashkenas/coffeescript#4989] opened 2018-02-25 06:16 UTC
coffeescript:

```coffee
sum = (xs) -> 
  for count in xs
    total += count
  total
```

JS output:
```js
var sum;

sum = function(xs) {
  var count, i, len;
  for (i = 0, len = xs.length; i < len; i++) {
    count = xs[i];
    **total** += count;
  }
  return **total**;
};
```

As you can see there is no local declaration for the variable total in the function, indeed there is no declaration at all.

**Comment by zdenko** [comment] 2018-02-25 07:49
Variable is not declared as there's no assignment.
Even with variable declared, given [example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAzgrgtgbgFBNnCBeCAzGA7AYwBcBLAezwAoAPKASggG8kIJRICz8iAaCEvgBsApnj5EyREIOStsZSJRKYIABiGiVtAHQi8AcyIALBPwgAeCHtMkA1LYbNWrTty1QA2iQC6siAEgJKUEIWyxXPCI_AF8WCDBhIhgwPAgg6WRYpGlhMCJKNEoPAEYeACZvOjoEIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=env&prettier=false&targets=Node-8.5&version=6.26.0&envVersion=1.6.2) would always return `NaN`.
```javascript
var sum;

sum = function(xs) {
  var count, i, len, total;
  for (i = 0, len = xs.length; i < len; i++) {
    count = xs[i];
    total += count;
  }
  return total;
}

alert(sum([1,2])); # NaN
```

**Comment by GeoffreyBooth** [comment] 2018-02-25 08:03
This is an interesting one. `total` [isn’t declared in CS1 either](http://coffeescript.org/v1/#try:sum%20%3D%20(xs)%20-%3E%20%0A%20%20for%20count%20in%20xs%0A%20%20%20%20total%20%2B%3D%20count%0A%20%20total).

@zdenko is right, it’s not declared because it’s never assigned, i.e. there’s never a `total = something` line. So the question is whether `+=` should be considered an assignment operator, like an “assign and increment” operator. Historically it never has been, but it’s a valid question as to whether `+=` should be considered as implying assignment. And ditto for `-=` and the rest of the JavaScript [assignment operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Assignment). @jashkenas or @lydell, can you provide any perspective on this from back when the variable assignment/scoping rules were being devised?

**Comment by vendethiel** [comment] 2018-02-25 10:24
Compound assignment operators never did declare.
We even have a special case for `a ?= b` to error out if `a` doesn't exist previously (`the variable "a" can't be assigned with ?= because it has not been declared before`).

Of note: Coco does error in the `a += b` case (... but not in the `a ?= b` case).

**Comment by lydell** [comment] 2018-02-25 10:28
I have never been involved in decisions around this before, but here are my thoughts.

There seems to be 3 ways to go here:

1. Don’t declare (current behavior)
2. Declare
3. Compile error (like for `a ?= 1`)

If we _did_ declare, I think that might be worse. It would change the function from throwing a `ReferenceError` into silently returning `NaN`. Makes it harder to find the mistake.

A compiler error could be nice, since it’s most likely a mistake. I wonder if we’ll break anyone’s code though.

Since `a += 1` is basically a shorthand for `a = a + 1` (which _does_ declare `a`) it could also be argued that we _should_ declare for consistency.

Tricky problem. Does it matter much in practice, though?

**Comment by zdenko** [comment] 2018-02-25 13:08
> a special case for a ?= b to error out if a doesn't exist previously

@vendethiel any special reason for this? I think in this case `a` could be declared cause there is an assignment.

```javascript
// a ?= 1
var a;
if (a == null) {
  a = 1;
}

// a == 1
```

Here is an overview of compound assignment:

a) Variable is declared. The result is `NaN`.

```coffeescript
a **= 1   # NaN
a //= 1   # NaN
a %%= 1   # NaN
```

b) No declaration and no compile error. Variable could be safely declared,  e.g. the result is not `NaN`.

```coffeescript
a |= 1    # 0
a ^= 1    # 0
a &= 1    # 0
a >>>= 1  # 0
a >>= 1   # 0
a <<= 1   # 0
```

c) No declaration and compile error. Could be safely declared.

```coffeescript
a &&= 1  # undefined
a ||= 1  # 1
a ?= 1   # 1
```

d) No declaration and no compile error. The result is `NaN`.

```coffeescript
a -= 1   # NaN
a += 1   # NaN
a /= 1   # NaN
a *= 1   # NaN
a %= 1   # NaN
```

Based on this, we could declare the variable  in cases where the result is not `NaN`, and  throw compiler error in other cases:

a) Declare variable

```coffeescript
a &&= 1
a ||= 1
a ?= 1
a |= 1
a ^= 1
a &= 1
a >>>= 1
a >>= 1
a <<= 1
```

b) Compile error

```coffeescript
a -= 1
a += 1
a /= 1
a *= 1
a %= 1
a **= 1
a //= 1
a %%= 1
```

**Comment by vendethiel** [comment] 2018-02-25 16:41
@zdenko because in that case, `?=` is *never* what you want.
If we made it declare, it’d act like `=`.

**Comment by GeoffreyBooth** [comment] 2018-02-26 01:43
In general, the CoffeeScript compiler should never be creating global variables, especially unexpectedly. The docs even say, albeit in an [unrelated section](http://coffeescript.org/#unsupported):

> The CoffeeScript compiler automatically takes care of declaration for you, by generating `var` statements at the top of every function scope. This makes it impossible to accidentally declare a global variable.

Having `+=` and its friends create global variables certainly seems to go against that promise. Though as @zdenko points out, almost all of the JavaScript assignment operators would produce unwanted values if we declared and then added/subtracted/etc. to them. To take just `+=` ([REPL](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBCA0EEYG4BQSQQNQF4IEYEQIIHoiIA5EMlODbAcgDMB7Ju_EiAVwDsATAUwYBLbv17MmKAMZNuAZyYAbfgDpFTAOYAKOiDqwQASmQz5S1eu104–MaRA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=es2015&prettier=false&targets=&version=6.26.0&envVersion=)):

```js
var a, b;

a += 1;     // NaN

b += 'foo'; // undefinedfoo
```

This would lead me to think we should be throwing a compiler error, unless anyone can think of a case where automatically declaring the variable as a result of `+=`/etc. is desired.

If there _is_ a case where this is reasonable behavior, then this becomes an issue for linting, and the compiler keeps the current behavior. If there isn’t, and I suspect that there isn’t, then I think it’s better to start throwing an error for this case rather than unexpectedly creating global variables. 

There is yet another option, in which there _is_ a reasonable case for the current behavior but it seems like a narrow edge case, and the case of “user error” seems more likely most of the time. In that case, we add the compiler error, and the user with the narrow reasonable edge case needs to add `a = undefined` above the `a +=` line to preserve the current behavior. We’re _adding_ a compiler error, not changing the compiler output, so no one in that situation should be surprised by code executing differently than it does now.

**Comment by lydell** [comment] 2018-02-26 07:10
`+=` does not create global variables. `a = 1` would (in non-strict mode), but `a += 1` is always a `ReferenceError` as far as I can tell. So CoffeeScript _isn't_ creating global variables. It lets you _reference_ global variables, such as in `alert(someGlobal)`.

**Comment by GeoffreyBooth** [comment] 2018-02-26 18:46
As usual, @lydell is correct:

```
» node -e 'a += 1'
[eval]:1
a += 1
^

ReferenceError: a is not defined
```

So the premise of this issue is incorrect. Since the runtime is already throwing an error, do we need to do anything? There _is_ a use case for incrementing an already-declared global variable, and the compiler has no way of knowing what variables are declared in the global scope, so there’s no way for compiler to catch this case and throw an error itself:

```coffee
# init.coffee
global.pokes = 0

# main.coffee
require './init'
pokes += 1
```

So do we close this as invalid?

**Comment by lydell** [comment] 2018-02-26 20:04
Well, neither way is clearly better than the other. And this isn't a big issue. So perhaps it's better to leave things be and not risk breaking backwards compatibility.

**Comment by jashkenas** [comment] 2018-02-26 20:10
This is working as intended, is not a bug, and should not be changed.

`+=` and `-=` are mutations of existing variables. In CoffeeScript, if the variable is defined in lexical scope, they'll mutate that variable. If it's not defined, it'll mutate the variable in an enclosing or the global scope.

This is the same as any other reference to a variable not present in lexical scope. It just falls back to whatever is in your JavaScript runtime.

If you changed this, you would make referring to and mutating external variables impossible.

**Comment by lydell** [comment] 2018-02-26 20:14
> If you changed this, you would make referring to and mutating external variables impossible.

Not _impossible,_ it'd be similar to how you must say for instance `window.foo = 5` to make a new global variable. Not saying that we should make this change, though :)

**Closed** 2018-02-26 21:52 UTC
Labels: invalid
