### ISSUE TITLE
Member assignment with function parameter bug in 1.9.3

### ISSUE THREAD

**Issue by pke** [jashkenas/coffeescript#4058] opened 2015-08-12 13:22 UTC
This code

```
ready: (element, @options) ->
    options.text or= "" 
```

gets compiled to this in < 1.9.3

```
ready: function(element, _options) {
      this.options = _options;
      _options.text || (_options.text = "");
```

and to this (imho) faulty code in 1.9.3

```
ready: function(element, options1) {
      this.options = options1;
      options.text || (options.text = "");
```
hence creating the unknown var `options`.

**Comment by michaelficarra** [comment] 2015-08-12 13:47
This is a duplicate of many others.

**Closed by michaelficarra** 2015-08-12 13:47 UTC

**Comment by pke** [comment] 2015-08-12 14:56
Would be nice to know the duplicate

**Comment by michaelficarra** [comment] 2015-08-12 15:15
#1007, #2987, #3168, #3272, #3318, #3891, #3927
