### ISSUE TITLE
Certain combinations of indentation will lead to incorrect placement of calls

### ISSUE THREAD

**Issue by joepie91** [jashkenas/coffeescript#3910] opened 2015-03-23 01:49 UTC
I've been working with a lot of functional constructs today, and I've now run into the same indentation issue twice. The below example shows the simplest case I've run into. I am not sure where the problem is being caused, and being unfamiliar with the Coffeescript internals, I am unable to reduce the testcase further.

Note the different placement in the JS of `profile.images =` vs `profile.tags =`, despite them being in conceptually the same place in the CS source. The former interpretation is as intended (and as it is normally interpreted).

Interpreting the `profile.tags =` statement one tab further 'solves' the issue in that it results in the correct interpretation, but obviously this is not a good idea :)

Source:

```coffeescript
# Does not bug:
		$ "#result-images"
			.each ->
				# Poor quality Google Images thumbnails, but eh. It'll do.
				profile.images ?= []

				imageList = $ this
					.find ".img-info-link img"
					.map -> $(this).attr "src"
					.get()

				profile.images = profile.images.concat imageList

# Bugs:
		$ "#result-tags"
			.each ->
				profile.tags ?= []

				tagList = $ this
					.find ".tag"
					.map ->
						tagName = $ this
							.children "a.tag-link"
							.text()
							.trim()

						tagSources = $ this
							.find ".tag-source a"
							.map -> $(this).attr "href"
							.get()

						{name: tagName, sources: tagSources}
					.get()

				profile.tags = profile.tags.concat tagList
```

Compiled JS:

```javascript
// Generated by CoffeeScript 1.9.1
(function() {
  $("#result-images").each(function() {
    var imageList;
    if (profile.images == null) {
      profile.images = [];
    }
    imageList = $(this).find(".img-info-link img").map(function() {
      return $(this).attr("src");
    }).get();
    return profile.images = profile.images.concat(imageList);
  });

  $("#result-tags").each(function() {
    var tagList;
    if (profile.tags == null) {
      profile.tags = [];
    }
    return tagList = $(this).find(".tag").map(function() {
      var tagName, tagSources;
      tagName = $(this).children("a.tag-link").text().trim();
      tagSources = $(this).find(".tag-source a").map(function() {
        return $(this).attr("href");
      }).get();
      return {
        name: tagName,
        sources: tagSources
      };
    }).get();
  });

  profile.tags = profile.tags.concat(tagList);

}).call(this);
```

**Comment by vendethiel** [comment] 2015-07-09 23:36
duplicate of #3866

**Closed by vendethiel** 2015-07-09 23:36 UTC
