### ISSUE TITLE
feature request - conditional in string interpolation

### ISSUE THREAD

**Issue by Inve1951** [jashkenas/coffeescript#4646] opened 2017-08-16 08:16 UTC
input:
```coffee
"""very long string #{if here then "here"}"""
```
current output:
```JS
`very long string ${(here ? "here" : void 0)}`;
```
expected output:
```js
`very long string ${(here ? "here" : "")}`;
```
current code for expected output:
```coffee
"""very long string #{if here then "here" else ""}"""
```

**Comment by lydell** [comment] 2017-08-16 08:39
Duplicate of #2992.

**Closed by lydell** 2017-08-16 08:39 UTC

**Comment by Inve1951** [comment] 2017-08-16 10:25
not a dupe imo

**Comment by lydell** [comment] 2017-08-16 10:27
What's the difference, then?

**Comment by Inve1951** [comment] 2017-08-16 10:31
#2992 is just a question about if this is intended
also #2992 doesn't discuss if it should be implemented

to me it seems like the current behavior of returning `undefined` exists only because nobody ever thought about what the behavior should be and hence the same _compilation_ as outside of strings/interpolation is applied

**Comment by Inve1951** [comment] 2017-08-17 23:04
`if a then b` should return nothing if `not a`.

Outside of strings `undefined` represents _nothing_ so that's fine there.
In a string however it's a whole 9 characters and _nothing_ would be best represented by an empty string.

With that argumentation i think `a ? b : ""` would make more sense for string interpolations.

I also think only conditionals should behave like that. Wouldn't want anything else to return the empty string.


Please let's discuss this instead of discarding it as a dupe and be done with it.

@lydell @GeoffreyBooth

**Comment by helixbass** [comment] 2017-08-17 23:34
@Inve1951 I'm with you, this was an upside when writing Copheescript (outputs PHP) since in PHP `null`'s string representation was the empty string. So you can write conditional interpolations way more naturally, postfix `if`/`else` are so smooth

And I don't know who *wants* `undefined` interpolated into their string, I'd think this would be the desired behavior 99% of the time

I'll take a look at how hard it would be to implement, maybe we can talk it into 2.0...

**Comment by GeoffreyBooth** [comment] 2017-08-18 01:36
I’ve been burned by `"Welcome, #{if user? then user.name}!"` becoming “Welcome, undefined!” on more than one occasion. I like the idea of this.

One issue though is how to deal with code farther down. For example:
```coffee
"a#{1 + (if b then c) + 2}d"
```

Does the “inline `if`” return an empty string only if it’s at the top level, i.e. the only thing in the interpolated code block, or does it return an empty string however far down it is? The latter would cause problems, especially with CSX, as there could be several lines of code inside such an interpolated block. But the former also presents a consistency issue, as it becomes this weird edge case where inline `if` returns an empty string and not `undefined`, and you just have to remember that that’s how it works in that situation and that situation only. I’m not sure the convenience of excluding `else` is worth the complexity of remembering these new rules regarding how `if then` behaves in various circumstances.

**Comment by helixbass** [comment] 2017-08-18 02:24
@GeoffreyBooth I think you're right that it could only be applied to top-level `if` clauses. So I think the question is how realistic/frequent the non-top-level cases are. Your example isn't particularly realistic. It seems like pretty much only in string concatenation operations would the string value of `undefined` be relevant, no? But then it's almost always easier/more "correct" to just use interpolation directly (rather than a concatenation nested inside an interpolation)

But agreed that it's a matter of weighing the inconsistency against the convenience/expectedness. I tend to think it's ok to hide a little magic if it feels more intuitive but wonder what realistic counterexamples there are

**Comment by GeoffreyBooth** [comment] 2017-08-18 02:40
What came to mind for me was the JSX example in the docs, which has this interpolation:

```coffee
    {if rating % 1 isnt 0
      <Star className="halfStar" />}
```

That’s a multiline `if`, but it’s still “top-level” . . . and JSX is just a fancy interpolated string, grammar-wise. I have a feeling that this “more complicated code in interpolations” may come up more often than we might think.

**Comment by Inve1951** [comment] 2017-08-18 02:51
I gave this some thought as well but didn't want to bloat my previous message.

In my opinion it should only return the empty sting at top level, anything further in would be treated as _regular_ code. I think that's the most straight forward behavior.

One more thing to think about:
```COFFEE
"""<input type="checkbox" #{("checked " if checked) + ("disabled" if disabled)}/>"""
```
versus
```COFFEE
"""<input type="checkbox" #{"checked " if checked}#{"disabled" if disabled}/>"""
```

Should it detect concatenation of these conditionals and have them return the empty string if `false`?
Or maybe wrapping it in parens still considers it top level?

I haven't had the pleassure with JSX/CSX yet so i can't comment on that.

**Comment by lydell** [comment] 2017-08-18 05:56
Wouldn't it be confusing that this refactor is a mistake?

```coffee
"a #{if b then 'b'}"
```
→
```coffee
bString = if b then 'b'
"a #{bString}"
```

**Comment by connec** [comment] 2017-08-18 09:35
I'd suggest that we change interpolations to implicitly wrap whatever is interpolated with `<expr> ? ''`. In that case, you're refactoring (@lydell) would be fine, e.g.:

```coffee
bString = if b then 'b'
"a #{bString}"
```

```js
var bString

bString = b ? 'b' : void 0
`a ${bString != null ? bString : ''}`
```

**Comment by Inve1951** [comment] 2017-08-18 12:06
I'm not sure that's a good idea. Just think of console.log debugging.

**Comment by lydell** [comment] 2017-08-18 12:30
@Inve1951 Then what's your response to my comment? :)

**Comment by Inve1951** [comment] 2017-08-18 12:42
I don't find it confusing as the feature documentation would clearly state it's for that specific case only. It could even come with a _bad_ example for more clarity.
Here's the fix for your snippet:
```COFFEE
bString = if b then 'b'
"a #{bString ? ''}"```

**Comment by connec** [comment] 2017-08-18 14:03
I disagree quite strongly to adding special-casing to specific operators, it feels a bit arbitrary to me (especially in lydell's example).

If you want `"undefined"` in a log statement you can:

```coffee
value1 = undefined
value2 = null

# log it as an argument
console.log 'value1=', value1, 'value2=', value2

# explicitly stringify it
console.log "value1= #{String value1} value2= #{String value2}"
```

**Comment by helixbass** [comment] 2017-08-18 14:41
Ya @lydell's example is the most damning (though all raise valid aspects), not being able to safely refactor into a function is not good

@Inve1951 it's not good programmer UX to introduce tricky cases that anyone might have to familiarize themselves with in order not to get stung. While you or I might be prepared to take that tradeoff, it's not a good language-level decision to force it on everyone

@connec your approach could work but still feels a little tricky/noisy (that could be a lot of added conditional code if you interpolate heavily)

Maybe we should even warn (do we do compile-time warnings?) if code contains an interpolation with top-level `if` and no `else` ("You probably meant `else ''`)?

**Comment by connec** [comment] 2017-08-18 15:18
It would be very noisy I suppose (especially in CS2 where interpolations are otherwise very clean now), but it does seem like something that could be quite useful.

I don't think we really do compiler warnings atm. I always feel that should be the purview of another tool (e.g. a linter).

**Comment by lydell** [comment] 2017-08-18 15:46
What do people think about the workaround from #2992?

```coffee
"a #{[if b then 'b']}"
```

**Comment by vendethiel** [comment] 2017-08-18 15:47
It has a pretty considerable overhead.

**Comment by connec** [comment] 2017-08-18 16:21
I think that would be too expensive to implement as default, i.e. creating a throwaway array for every interpolation, whose `toString` must be called, is *probably* more expensive than a conditional... though I haven't benchmarked and know very little about the performance characteristics of such things.

We could provide cleaner output at the cost of a function invocation by making a helper:

```js
var toString = s => s != null ? s : '', bString

bString = b ? 'b' : void 0
`a ${toString(bString)}`
```

But that may also qualify as "considerable overhead" when interpolating heavily.

**Comment by Inve1951** [comment] 2017-08-28 15:20
I'd say CSX should as well have the expected behavior, whatever that might be in that case.
