### ISSUE TITLE
prosopal: Nested loops break/continue.

### ISSUE THREAD

**Issue by aa6** [jashkenas/coffeescript#4254] opened 2016-04-14 15:53 UTC
```coffeescript
for row in rows
  for item in row
    if item is 'ok'
      continue 2
    if item is 'stop'
      break 2
  # ...
```

**Comment by vendethiel** [comment] 2016-04-14 16:11
This is a duplicate of #54 (i guess you come from PHP where numbers are used like in this issue)

**Closed** 2016-04-14 16:14 UTC

**Comment by aa6** [comment] 2016-04-14 16:16
Yes, numbers are used in PHP in that manner. Could you provide a good replacement for this statements? If not, please reopen the issue.

**Comment by aa6** [comment] 2016-04-14 16:18
It's also not a duplicate of #54 because I'm not asking for labels.

**Comment by milleniumbug** [comment] 2016-04-14 20:20
"But PHP has it" is never a good reason to introduce a feature, considering how [badly designed PHP is](https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/). Indeed, if I was a language designer, I'd be going as far away from the badness as I could. Remember, this project is "JavaScript: the good parts". This is out of scope.

Good replacement? Dunno, maybe `return`? Make your functions smaller, it's good for you.

**Comment by carlsmith** [comment] 2016-04-14 20:27
+1 on using return to break out of nested loops. -1 on adding this feature. Just use `do` with a lambda, and put your loops in the body.

**Comment by aa6** [comment] 2016-04-15 04:26
"But PHP has it" was never a reason to open this issue. And I must admit that "but PHP has it" is never a good reason to close issues on github without any other explanation because it's an [argument from authority](https://en.wikipedia.org/wiki/Argument_from_authority).

Thank you for the replies, now I see that probably using `do` with lambda is a better solution to my issue:

```coffeescript
name_column_index = do -> loop 
  for item,index in data.shift()["table:table-cell"]
    switch item["text:p"]
      when "header1","header2"
        break
      when "search_name"
        return index
```

The solution I strongly dislike:

```coffeescript
loop
  break_the_loop = false
  for item,index in data.shift()["table:table-cell"]
    switch item["text:p"]
      when "header1","header2"
        break_the_loop = true
      when "search_name"
        name_column_index = index
  break if break_the_loop
```

What I was thinking about:

```coffeescript
loop for item,index in data.shift()["table:table-cell"]
  switch item["text:p"]
    when "header1","header2"
      break
    when "search_name"
      name_column_index = index
      break 2
```
