### ISSUE TITLE
Unable to pass transpile option to `require('coffeescript/register')`

### ISSUE THREAD

**Issue by suprMax** [jashkenas/coffeescript#4769] opened 2017-11-01 16:19 UTC
We're using React and deprecated `coffee-react` to run our server in dev mode. We were trying to upgrade to new CoffeeScript and noticed that there is no way to pass `transpile` option. Without this option our server won't run. Here is how babel-register does this: `require('babel-register')({ extensions: ['.es'] });`;

Am I missing something or is it not supported yet?

P.S.
Looking through source I noticed this https://github.com/jashkenas/coffeescript/blob/master/src/register.coffee#L8 but that is always `undefined` and I couldn't find any documentation regarding nodejs support for this.

Attempting to monkey patch `CoffeeScript.compile` results in an error like this:
```
const func = CoffeeScript.compile;
CoffeeScript.compile = (filename, options) => (
  func(filename, Object.assign({}, options, { transpile: require('./coffeerc') }))
);
CoffeeScript.register();
```

```
/Users/max/Projects/frontend/node_modules/coffeescript/lib/coffeescript/index.js:170
      throw helpers.updateSyntaxError(err, stripped, filename);
      ^

SyntaxError: Unexpected token z in JSON at position 0 (While processing preset: "/Users/max/Projects/frontend/node_modules/babel-preset-es2015/lib/index.js")
```

Not yet sure how the options are passed exactly.

**Comment by GeoffreyBooth** [comment] 2017-11-01 17:09
`coffeescript/register` does not accept options. What version of CoffeeScript are you using?

**Comment by suprMax** [comment] 2017-11-01 17:12
The latest, 2.0.2

**Comment by GeoffreyBooth** [comment] 2017-11-01 17:25
In 2.0.2 we added the option for `transpile` to be passed down to `require`d files. You need to be running the root `coffee` process with that option for this to be the case.

`transpile` is only intended as a convenience for command-line testing. It’s not intended for use as part of a build chain, or as part of a running server. I suggest you set up a proper build chain using something like Gulp or Webpack or Browserify, that can compile and transpile all your `.coffee` files into JavaScript and then serve the resulting JavaScript.

**Comment by suprMax** [comment] 2017-11-01 19:32
Yes we have that in production but for development it is often more convenient to just use require hooks

**Comment by GeoffreyBooth** [comment] 2017-11-01 20:07
Since `register` isn’t intended to accept options, I’m closing this issue. If you can isolate a bug on CoffeeScript’s side regarding `transpile` not getting passed down to required files even when `coffee` is run with `--transpile`, or the Node API is used with `transpile` passed in the options, please open a new issue with steps to reproduce.

**Closed by GeoffreyBooth** 2017-11-01 20:07 UTC

**Comment by suprMax** [comment] 2017-11-02 11:33
@GeoffreyBooth any chance of making "register" call configurable in future versions? This is a blocker for us, we don't want to precompile our tests before running them, implementing a server precompilation during dev is cumbersome too.

**Comment by GeoffreyBooth** [comment] 2017-11-02 15:05
As I said above, it will transpile if you run CoffeeScript with that option. How are you running the Node process? If you start it via e.g. `coffee --transpile` the required files should be transpiled.

**Comment by suprMax** [comment] 2017-11-02 15:15
Nope, I start via `node ...` because we're transitioning from coffee to babel and need to transpile both on the fly. We have a `require_hooks.js` file that is loaded in the app first. We also use the same file to patch environment for tests (mocha). I suppose I could start the server via `coffee` command locally, however the problem with tests will still remain.

**Comment by GeoffreyBooth** [comment] 2017-11-02 17:12
You can pass options to `register` by adding an `options` object to the `module` prototype. Here’s a working example:

`index.js`:
```js
require('module').prototype.options = {transpile: {presets: ['env']}};

require('coffeescript/register');

mod = require('./mod.coffee');
mod.talk();
```
`mod.coffee`:
```coffee
import path from 'path'

module.exports =
  talk: ->
    console.log path.sep
```
When run via `node index.js`, it prints `/` (on Mac/Linux).

**Comment by suprMax** [comment] 2017-11-02 17:14
ah thanks! I guess it's about the same as my hack above with wrapping `compile` method

**Comment by champel** [comment] 2018-09-11 18:13
I wanted to execute the `src/array.test.coffee` test with Mocha:
```coffeescript
import * as assert from 'assert'

describe 'Array', () ->
  describe '#indexOf()', () ->
    it 'should return -1 when the value is not present', () ->
      assert.equal [1,2,3].indexOf(4), -1
```

Using the following command:
```
npx mocha --require coffeescript/register "src/**/*.test.coffee"
```
But I had this exception:
```
src/array.test.coffee:1
(function (exports, require, module, __filename, __dirname) { import * as assert from 'assert';
                                                                     ^
SyntaxError: Unexpected token *
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
    ...
```
I applied the following solution in order to be able to use import and export keywords from Mocha tests:

Run the commands to install Install babel packages:
```
npm install --save-dev @babel/core @babel/preset-env @babel/register
npm install --save-dev babel-core@7.0.0-bridge.0
```
Note: the second install command is to avoid the following error (a bug?):
```
  Error: To use the transpile option, you must have the 'babel-core' module installed
  ...
```

Create a `babel.config.js` file in the root of the project to configure babel:
```javascript
const presets = ["@babel/env"];
module.exports = { presets };
```

Create a `coffee.config.js` file to configure coffeescript to transpile the code using the Babel configuration:
```javascript
require('module').prototype.options = {
  transpile: require('./babel.config')
};
require('coffeescript/register');
```
I changed the command in the following way:
```
npx mocha --require ./coffeescript.config.js "src/**/*.test.coffee"
```
Then, the library was imported correctly:
```
  Array
    #indexOf()
      ✓ should return -1 when the value is not present

  1 passing (6ms)
```
My final version of the command has been:
```
npx mocha --require @babel/register --require ./coffeescript.config.js "src/**/*.test.{js,coffee}"
```
Where I'm able to execute not only coffeescript imports but also javascript imports.

**Comment by laurentpayot** [comment] 2018-09-12 08:33
Does https://github.com/jashkenas/coffeescript/issues/4769#issuecomment-341492901 help you?

**Comment by laurentpayot** [comment] 2018-10-10 13:57
Thanks @champel! The `coffeescript.config.js` trick is working great with mocha.

Also no need to install Babel bridge for CoffeeScript 2.3.2+.
