### ISSUE TITLE
Bug: Last JSX tag returned, when compiler should throw error

### ISSUE THREAD

**Issue by remoteportal** [jashkenas/coffeescript#5034] opened 2018-04-15 20:18 UTC
Because of the parenthesis BOTH <Row> tags should be included in the return statement.  In error only the last one is:

CoffeeScript:
```coffee
		JSXFunction = -> (
				<Row>ABC</Row>
				<Row>DEF</Row>
			)
```

Errant JavaScript:
```js
// Generated by CoffeeScript 2.2.4
  JSXFunction = function() {
        <Row>ABC</Row>;
        return <Row>DEF</Row>;
      };
```

Correct JavaScript:
```js
  JSXFunction = function() {
        return <Row>ABC</Row>
            <Row>DEF</Row>;
      };
```

**Comment by connec** [comment] 2018-04-15 22:59
~~~Unless I'm missing something, [that JavaScript doesn't compile](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBAVhAHgMQK5mFAluGBeGAM3UxzBgAoBKGAbwCgYYAnAUylWfIB4ATLAG4A-bgHp-wxjACQfQSPHyA3PQC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=react&prettier=false&targets=&version=6.26.0&envVersion=).~~~

Ah, I take it that's the point - that the CoffeeScript makes for a hard-to-catch bug?

**Comment by microdou** [comment] 2018-04-16 14:33
I don't think it's a bug. I believe that you cannot return two jsx fragments at the same time.

You have to manually wrap the two jsx tags into one using either `array`, or the new `Fragment` notation in React, as follows:
```coffeescript
f = -> [<A />, <B />]

f = ->
  <>
    <A />
    <B />
  </>
```

**Comment by GeoffreyBooth** [comment] 2018-04-17 06:39
@xixixao, your thoughts?

**Comment by zdenko** [comment] 2018-04-17 07:16
@GeoffreyBooth I think @microdou is right. JSX elements must be wrapped in an enclosing tag ([example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAUgygGgMQK4DsDGAXAlgexRAXggDNVNcUAKASggG8AoASDAFMMkx9KGI_-APACUcAdwB8AQQBCAYQEB6EROZ9hY8QBEAogkXLxvfhGoBuCAwC-phkA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=react%2Cenv&prettier=false&targets=Node-9.8&version=6.26.0&envVersion=1.6.2))

This [JS example](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAUgygGgMQK4DsDGAXAlgexRAXggDNVNcUAKASggG8AoASDAFMMkx8AeAEy2AA-BhFFjuAJRwB3QQEEAQgGFuAeimzmoyTMEARAKII1G4WO2r-QgNwMAvraA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=react%2Cenv&prettier=false&targets=Node-9.8&version=6.26.0&envVersion=1.6.2) works:
```javascript
var JSXFunction = function() {
  return <div>
    <Row>ABC</Row>
    <Row>DEF</Row>
  </div>;
};
```

Also [this](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=G4QwTgBAUgygGgMQK4DsDGAXAlgexRAXggDNVNcUAKASggG8AoCCMAUwyTHwG0nmIAPACUcAdwB8AQQBCAYQEB6ERIA0DAJDCx4gCIBRBIuXi-AXQDcDAL6WgA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=react%2Cenv&prettier=false&targets=Node-9.8&version=6.26.0&envVersion=1.6.2)

```javascript
var JSXFunction = function() {
  return [
    <Row>ABC</Row>,
    <Row>DEF</Row>
  ];
};
```

**Comment by connec** [comment] 2018-04-17 10:03
I think maybe the issue is that if you mistakenly typed:

```js
jsxFunction = () => (
    <Row>ABC</Row>
    <Row>DEF</Row>
)
```

In JavaScript, you would get a [syntax error](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FYZwHgYgrgdgxgFwJYHsYAIC86AUBKLAPlwCh1z0AeAJRQHdCBBAIQGFKB6Whsim-wgBEAohE7dCJPEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=react&prettier=false&targets=&version=6.26.0&envVersion=) whereas in CoffeeScript [the second tag is returned]:

```coffee
jsxFunction = () => (
    <Row>ABC</Row>
    <Row>DEF</Row>
)
```

```js
var jsxFunction;

jsxFunction = () => {
  <Row>ABC</Row>;
  return <Row>DEF</Row>;
};
```

Personally, I didn't realise `()` had the same comma-ellision as `{}` and `[]`:

```coffee
(
  1
  2
  3
)
# becomes (1, 2, 3)
```

[the second tag is returned]: http://coffeescript.org/v2/#try:jsxFunction%20%3D%20()%20%3D%3E%20(%0A%20%20%20%20%3CRow%3EABC%3C%2FRow%3E%0A%20%20%20%20%3CRow%3EDEF%3C%2FRow%3E%0A)

**Comment by microdou** [comment] 2018-04-17 15:12
My understanding is @remoteportal wants the function to return two JSX elements which really doesn't work that way.

@connec made a good point. CoffeeScript should raise an error if a user intends to return adjacent JSX elements, just as JavaScript does.
`Adjacent JSX elements must be wrapped in an enclosing tag`

**Comment by stevefan1999** [comment] 2018-04-25 14:11
You cannot do this in JS either. You need to return an array or fragment.

**Comment by GeoffreyBooth** [comment] 2018-04-25 17:10
Yes, I think the bug is that CoffeeScript returns the closing tag, rather than throwing an error.

**Comment by GeoffreyBooth** [comment] 2018-04-28 03:10
@xixixao or @zdenko, do either of you want to take a crack at making sure code like the following throws an [error](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=FYZwHgYgrgdgxgFwJYHsYAIC86AUBKLAPlwCh1z0AeAJRQHdCBBAIQGFKB6Whsim-wgBEAohE7dCJPEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=true&presets=react&prettier=false&targets=&version=6.26.0&envVersion=), rather than compiling to incorrect JSX?

```coffee
render = -> (
  <Row>ABC</Row>
  <Row>DEF</Row>
)

**Closed** 2018-05-01 15:09 UTC
Labels: bug

**Comment by GeoffreyBooth** [comment] 2018-05-02 05:50
@remoteportal @stevefan1999 @connec @microdou @zdenko please see https://github.com/jashkenas/coffeescript/pull/5046#issuecomment-385827030. I think my fix might’ve made things worse. I would appreciate your feedback.

**Comment by zdenko** [comment] 2018-05-02 13:11
@GeoffreyBooth hold my beer. #5049
